extends RefCounted

## Hand-authored semantic labels for SEQ slots, per [sprite type](../../docs/context/18-sprite-layers.md).
##
## Loads `<content_root>/sprites/animation_names.json` — the host declares the root
## (`SpriteRigContentRoot`), the file is built by `tools/build_animation_names.py`
## from TacticsEngineG's CSV — see that script's docstring. Provides
## `get_label(sprite_type, slot)` for any consumer that wants the wiki name
## of a SEQ slot — primarily the resolution viewer's readout panel and any
## future atlas-aware tooling.
##
## This is a [hand-authored data asset](../../docs/context/01-asset-extraction.md)
## — checked into git, not regenerated by `bootstrap_assets.sh`. Re-run the
## converter manually when TacticsEngineG updates its labels.

## ADR-0212 dec. 1 — the class is INTERNAL to this addon; the host reaches it as
## `ExMateriaSpriteRig.AnimationNames`. `ContentRoot` is the addon's own install
## script and `JsonAsset` is the port's, which a portable addon is allowed to name
## (ADR-0139 dec. 12, `plugin.cfg` `deps=`).
const ContentRoot = preload("res://addons/exmateria_sprite_rig/install/SpriteRigContentRoot.gd")
const JsonAsset = ExMateriaPlatform.JsonAsset

## #809 / ADR-0202 — the labels are ROM-JOINED CONTENT the addon does not ship, so
## the address is the host's to declare. Moving the class alone would not have paid
## the burn-down row: a `res://assets/` literal travelling INTO an addon root lands
## on `check_addon_portability` arm 6 the moment it arrives, which is why the answer
## was always the injected content root and not a second `git mv`.
static func path() -> String:
	return ContentRoot.resolve(ContentRoot.ANIMATION_NAMES_SUBPATH)

static var _data: Dictionary = {}
static var _loaded: bool = false


static func _ensure_loaded() -> void:
	if _loaded:
		return
	_data = JsonAsset.load_dict(path())
	_loaded = true


## Return the hand-authored label for `(sprite_type, slot)`, or empty string
## if the combination has no label. `sprite_type` is case-insensitive; matches
## the lowercase keys used in `state_animations.json` (type1 / type2 / type3 /
## mon / cyoko / ruka / arute / kanzen / other / wep1 / wep2 / eff1 / eff2).
static func get_label(sprite_type: String, slot: int) -> String:
	_ensure_loaded()
	if slot < 0:
		return ""
	var key := sprite_type.to_lower()
	var type_data: Dictionary = _data.get(key, {})
	return String(type_data.get(str(slot), ""))


## Convenience that returns a "slot — label" string, or just "slot" when no
## label exists. Useful for one-line panel readouts.
static func format(sprite_type: String, slot: int) -> String:
	if slot < 0:
		return "—"
	var label := get_label(sprite_type, slot)
	if label.is_empty():
		return str(slot)
	return "%d — %s" % [slot, label]
