extends Node2D
## [b]NOT A TEST[/b] — an interactive eyeball-picker, renamed from `CursorClutPreviewTest`
## (#585). Arrow keys step a CLUT candidate row so a human can look at it; it asserts
## nothing and prints no verdict, so any sweep that globs `tests/*.tscn` and greps for
## FAIL reads it as a pass. It is correctly absent from `run_all_tests.sh` and declares
## `[NOT_A_TEST]` below, which is what `check_test_list_coverage.py` reads — the NAME was
## the whole of the remaining trap.
## Cycle through every plausible CLUT on tpage 0x1F so we can eyeball-pick the
## one that matches the in-game tile-cursor. The candidate set is generated by
## tools/parse_cursor_clut_candidates.py — see that script's docstring for the
## row layout (asset region 1 + region 2 + BATTLE.BIN runtime palettes).
##
## Controls:
##   LEFT / RIGHT  — step palette_row by 1
##   UP / DOWN     — step by 5
##   HOME          — jump to row 0
##   END           — jump to last row
##
## IT ENDS ON ITS OWN (#504). It used to have no exit condition, so any run that
## selected it paid the full `timeout 360` and scored HUNG — a rig is allowed to assert
## nothing, it is not allowed to hang. Unattended it now walks every candidate row on a
## STEP_TIME dwell and quits; touch any key and the sweep stops, because the by-eye
## session is what the rig is for.
##
## AND ITS OUTPUT SURVIVES THE TERMINATION. The picture is the point, but an unattended
## run has no eye on it, so the candidate table is PRINTED once up front — that way the
## run produces the catalogue rather than nothing at all.
##
## NOTE the input is generated and gitignored: `assets/sprites/textures/` is ignored
## wholesale, so RANGETILE.cursor_clut_candidates.json is absent on a fresh checkout and
## this rig takes the error path below until you run the generator its docstring names.

const CANDIDATES_JSON := "res://assets/sprites/textures/RANGETILE.cursor_clut_candidates.json"

@onready var _sprite: Sprite2D = $Sprite2D
@onready var _label: Label = $Hud/Label

var _rows: Array = []
var _row_idx: int = 0
## Unattended sweep. One dwell per candidate row, then quit — the budget is the exit
## condition the rig never had. A key press hands the session to the human and cancels it.
const STEP_TIME := 0.4
## Wall clock, for the same reason the GPU rigs use it: the dwell is a real-time pacing
## for a human eye, and the sweep's end is this scene's bound under `timeout 360`.
var _t0_ms := Time.get_ticks_msec()
var _manual := false


func _ready() -> void:
	# #463/#504: a rig, not a test. Declared FIRST so it is on the record even on the
	# two error paths below — which now quit instead of returning into an idle process.
	print("[NOT_A_TEST] a by-eye CLUT picker for the tile cursor — it cycles candidate palettes for a human to compare, and asserts nothing")
	var f := FileAccess.open(CANDIDATES_JSON, FileAccess.READ)
	if f == null:
		push_error("missing %s — run tools/parse_cursor_clut_candidates.py" % CANDIDATES_JSON)
		get_tree().quit(1)
		return
	var data: Variant = JSON.parse_string(f.get_as_text())
	if data == null or not (data is Dictionary) or not data.has("rows"):
		push_error("malformed candidates JSON")
		get_tree().quit(1)
		return
	_rows = data["rows"]
	_print_catalogue()
	# Default starting row: BATTLE.BIN yellow_a (the disasm-evidence pick).
	for i in _rows.size():
		var r: Dictionary = _rows[i]
		if r.get("source") == "battle_bin" and r.get("name") == "yellow_a":
			_row_idx = i
			break
	_apply_row()


## The candidate table, printed once so an unattended run emits something an eye was
## never going to be there to see.
func _print_catalogue() -> void:
	print("[cursor-clut] %d candidate rows:" % _rows.size())
	for i in _rows.size():
		var r: Dictionary = _rows[i]
		print("[cursor-clut]   row %3d  source=%-12s slot=%3d  clut_word=0x%04x  %s" % [
			i, str(r.get("source", "?")), int(r.get("slot", -1)),
			int(r.get("clut_word", 0)), str(r.get("name", ""))])


func _process(_delta: float) -> void:
	if _manual or _rows.is_empty():
		return
	var elapsed := float(Time.get_ticks_msec() - _t0_ms) / 1000.0
	var want: int = int(elapsed / STEP_TIME)
	if want >= _rows.size():
		print("[cursor-clut] done — swept %d rows in %.1fs" % [_rows.size(), elapsed])
		get_tree().quit(0)
		return
	if want != _row_idx:
		_row_idx = want
		_apply_row()


func _unhandled_input(event: InputEvent) -> void:
	if not (event is InputEventKey):
		return
	var key_event: InputEventKey = event
	if not key_event.pressed or key_event.echo:
		return
	# A human is here. Stop the sweep and the budget — the by-eye comparison is the
	# point of the rig, and it must not be cut off mid-look.
	_manual = true
	var key: int = key_event.keycode
	if key == KEY_LEFT:
		_step(-1)
	elif key == KEY_RIGHT:
		_step(1)
	elif key == KEY_DOWN:
		_step(5)
	elif key == KEY_UP:
		_step(-5)
	elif key == KEY_HOME:
		_row_idx = 0
		_apply_row()
	elif key == KEY_END:
		_row_idx = _rows.size() - 1
		_apply_row()


func _step(d: int) -> void:
	if _rows.is_empty():
		return
	_row_idx = (_row_idx + d) % _rows.size()
	if _row_idx < 0:
		_row_idx += _rows.size()
	_apply_row()


func _apply_row() -> void:
	if _rows.is_empty():
		return
	var mat := _sprite.material as ShaderMaterial
	if mat:
		mat.set_shader_parameter("palette_row", _row_idx)
	var r: Dictionary = _rows[_row_idx]
	var name_str: String = r.get("name", "")
	var name_tag := ""
	if name_str != "":
		name_tag = "  %s" % name_str
	_label.text = "row %d / %d   source=%s  slot=%d  clut_word=0x%04x%s\n[LEFT/RIGHT step  UP/DOWN ±5  HOME/END jump]" % [
		_row_idx, _rows.size() - 1,
		r.get("source", "?"),
		int(r.get("slot", -1)),
		int(r.get("clut_word", 0)),
		name_tag,
	]
