extends Node
# test-kind: logic
# seeded-break (arms 6-8): drop the `clampf` in src/gpu/ProvisionalObjective.gd's `_ongoing` (return the bare `0.5 * (hp_share + alive_share)`) — arm 6 reds on its SATURATED fixture, `_ongoing(1600, 0, 8, 0)`, which now scores exactly 1.0 and ties an actual terminal win, destroying the one property that lets a hand-written objective drop the invented terminal weight. ⚠️ It reds on that fixture and on NO other: a merely crushing position (enemy on 1 HP, one unit standing) scores 0.944 and stays under a win with the clamp gone, which is how the first cut of this arm went green against the seed and proved nothing. Everything else stays green either way — every value is still in [0, 1], the perspectives still sum to 1, and every candidate still ranks. Or: collapse the terminal band — make `_terminal` return a bare `1.0` / `0.0` instead of ordering by `spent` — and arm 6 reds on the two lost-cheaply/lost-dearly checks, which is the defect that was MEASURED in a real Gariland beat (all 64 candidates tied at 0.0 and the AI held a lost position). Or (arm 8): delete the `ticks <= 0` refusal — a zeroed record reads as RESULT_TEAM_0_WINS == 0 and scores a perfect 1.0 for team 0. Or (arm 9): make `check_horizon` return `agrees: true` for the UNCALIBRATED kind, restoring the silent pass #1109 removed.
# seeded-break: collapse the self/enemy perspective in src/gpu/RolloutValueFunction.gd:101 (`var s := "team0" if team == Team.TEAM_0 else "team1"` -> the same expression as `e`), so every feature cancels and the scorer returns exactly 0.5 for every row and both perspectives. This is the defect arm 1 is built for and the reason it must be a CROSS-LANGUAGE pin: 0.5 is a valid probability, the candidates still rank, nothing crashes — only the Python-fitted expectations catch it ('GDScript scored 0.500000000, Python fitted 0.026736970'), and they red across every fixture row in both team perspectives

## THE ROLLOUT OBJECTIVES' guards — both of them (#896 / #1109, GambitBattle §8,
## ADR-0253 / ADR-0274). No GPU, no frame.
##
## Arms 1-5 are the fitted value function `f`; arms 6-10 are
## [ProvisionalObjective] and the selection around it. They share a process on
## purpose (charter clause 13): the setup they share is "none", so splitting them
## would buy nothing and cost a 2.3 s Godot boot forever.
##
## 🔴 ARM 1 IS A CROSS-LANGUAGE PIN, AND IT IS THE ONLY THING THAT CAN CATCH THE
## DEFECT THIS FILE EXISTS FOR. `RolloutValueFunction.feature_vector` and
## `features_from` in `tools/fit_value_function.py` are the SAME FUNCTION
## WRITTEN TWICE, in two languages. Coefficients fitted against one definition
## and applied to the other fail completely invisibly: every score is still a
## probability in [0, 1], every candidate still ranks, no assertion anywhere
## goes red, and the AI simply plays worse than its own calibration report says
## it does. There is no crash and no wrong-looking number to notice.
##
## So the fixture carries INPUT ROWS and the EXPECTED SCORES the Python scorer
## produced from them — not feature vectors. A fixture of vectors would pin the
## features while leaving the intercept and the coefficient lookup unpinned, and
## those are half the arithmetic.
##
## 🔴 THE FIXTURE IS GENERATED BY THE THING UNDER TEST'S COUNTERPART, WHICH IS
## THE POINT AND ALSO THE TRAP. Regenerating it with a broken Python scorer
## would move the expectations to match, and this arm would stay green — the
## `families()` / `FAMILIES` shape #895 found, where a seed deleted its own
## check. What stops it here is that the fixture is COMMITTED and regenerating
## it is a reviewable diff: a change to the feature definition shows up as 24
## changed expectations, not as silence.
##
## Run: godot --path . --quit-after 600 res://tests/RolloutValueFunctionTest.tscn

const FIXTURE := "res://tests/fixtures/rollout_value_function_cases.json"

## Float equality across a JSON round trip and two languages' `exp`.
##
## 1e-8 rather than a comfortable 1e-6, because the headroom was measured. The
## fixture is built from the SHIPPED (6-dp-rounded) coefficients, the same ones
## GDScript reads, so the residual is pure float noise: 4.95e-10 across all 24
## cases. A first version built the fixture from the RAW fit instead, and the
## rounding alone cost 6.4e-7 — under a 1e-6 tolerance, so it passed, while
## leaving this arm blunt enough that a small feature error could hide inside
## the budget. The number to keep an eye on is the worst-disagreement line the
## arm prints, not this constant.
const TOLERANCE := 1e-8

var _failed := false
var _checks := 0


func _ready() -> void:
	_test_matches_the_python_scorer()
	_test_perspectives_are_complementary()
	_test_malformed_row_refuses()
	_test_ranking_averages_seeds_and_ties_to_the_incumbent()
	_test_every_feature_has_a_coefficient()
	_test_provisional_terminal_verdicts_dominate_every_ongoing_state()
	_test_provisional_ignores_mp_and_standoff_where_the_fit_does_not()
	_test_provisional_refuses_what_it_cannot_score()
	_test_horizon_guard_has_three_states_and_only_one_is_silent()
	_test_the_selected_objective_resolves()
	if _failed:
		print("[FAIL] RolloutValueFunction test")
	else:
		print("[PASS] RolloutValueFunction: %d checks — the fitted scorer matches the Python fit, perspectives complement, refusals refuse, ranking averages seeds and ties to the incumbent; the provisional objective dominates terminally, orders inside its terminal band without crossing it, ignores MP and standoff where the fit does not, refuses an unwritten record, and its horizon stance is never a silent pass" % _checks)
	get_tree().quit()


func _fail(message: String) -> void:
	_failed = true
	print("  [FAIL] %s" % message)


func _check(condition: bool, message: String) -> void:
	_checks += 1
	if not condition:
		_fail(message)


## ARM 1 — every fixture case scores what Python said it scores.
func _test_matches_the_python_scorer() -> void:
	var cases := _load_cases()
	if cases.is_empty():
		_fail("fixture %s has no cases — regenerate with tools/fit_value_function.py" % FIXTURE)
		return
	var vf := RolloutValueFunction.new()
	if not vf.is_loaded():
		_fail("the calibrated artifact did not load")
		return
	var worst := 0.0
	for case in cases:
		var row: Dictionary = case["row"]
		var expected: Dictionary = case["scores"]
		for team in [0, 1]:
			var got := vf.score(row, team)
			var want := float(expected[str(team)])
			worst = maxf(worst, absf(got - want))
			_check(absf(got - want) <= TOLERANCE,
				"team %d: GDScript scored %.9f, Python fitted %.9f (row %s)" % [
					team, got, want, str(row)])
	# `%.3e` is NOT a GDScript format specifier — it raises "unsupported format
	# character" and prints the template verbatim, so the number this arm exists
	# to report never appears.
	print("  [arm 1] %d cases x 2 perspectives, worst disagreement %.12f" % [
		cases.size(), worst])


## ARM 2 — `f(state, team0)` and `f(state, team1)` must sum to 1.
##
## Not a restatement of arm 1. The feature vector is built to MIRROR, and the
## mirrored corpus makes the fitted coefficients exactly antisymmetric, so this
## identity is a property the whole design rests on: a candidate's gain has to be
## its opponent's loss or ranking two sides of one battle is incoherent. A
## feature that failed to mirror — one battle-wide term with no per-team split,
## which is what `R_ENGAGE_SUM` was before it became a pair — breaks this while
## leaving arm 1 perfectly green, because arm 1 pins GDScript to Python and both
## would be wrong the same way.
func _test_perspectives_are_complementary() -> void:
	var vf := RolloutValueFunction.new()
	if not vf.is_loaded():
		return
	for case in _load_cases():
		var row: Dictionary = case["row"]
		var total := vf.score(row, 0) + vf.score(row, 1)
		_check(absf(total - 1.0) <= 1e-9,
			"perspectives should sum to 1, got %.12f" % total)


## ARM 3 — a row that is not a result record is refused, not scored.
func _test_malformed_row_refuses() -> void:
	var vf := RolloutValueFunction.new()
	if not vf.is_loaded():
		return
	# -1 and not 0.5: every value in [0, 1] is a legitimate probability, so an
	# error that returned one would rank a broken candidate at the median and
	# nothing downstream could tell it from a genuine coin flip.
	_check(vf.score({}, 0) < 0.0, "an empty row should refuse")
	_check(vf.score({"team0_hp": 10}, 0) < 0.0, "a partial row should refuse")
	_check(vf.feature_vector({"candidate": 0}, 0).is_empty(),
		"a row with no record fields should yield no vector")


## ARM 4 — ranking averages over the CRN seeds, and a tie goes to the incumbent.
func _test_ranking_averages_seeds_and_ties_to_the_incumbent() -> void:
	var vf := RolloutValueFunction.new()
	if not vf.is_loaded():
		return

	# Candidate 1 wins one seed hugely and loses the other; candidate 0 is level
	# on both. Ranking individual SLOTS would hand it to candidate 1's lucky
	# seed — which is exactly the bias common random numbers exist to remove.
	var strong := _record(1400, 200, 6, 1)
	var weak := _record(200, 1400, 1, 6)
	var level := _record(800, 800, 4, 4)
	var rows: Array = [
		{"candidate": 0, "seed_index": 0, "battle": 0}.merged(level),
		{"candidate": 0, "seed_index": 1, "battle": 1}.merged(level),
		{"candidate": 1, "seed_index": 0, "battle": 2}.merged(strong),
		{"candidate": 1, "seed_index": 1, "battle": 3}.merged(weak),
	]
	var ranked := vf.rank_candidates(rows, 0)
	_check(ranked.size() == 2, "two candidates in, two ranked out (got %d)" % ranked.size())
	if ranked.size() == 2:
		for entry in ranked:
			_check(int(entry["seeds"]) == 2,
				"candidate %d averaged %d seeds, expected 2" % [entry["candidate"], entry["seeds"]])
		var slot_best := maxf(vf.score(strong, 0), vf.score(weak, 0))
		_check(float(ranked[0]["value"]) < slot_best,
			"the winner's mean should be below the best single SLOT, else seeds were not averaged")

	# An exact tie must fall to candidate 0 — ADR-0246 dec. 2's incumbent.
	# Without this the AI re-plans a working posture every single turn on a
	# score it did not actually beat.
	var tied: Array = [
		{"candidate": 3, "seed_index": 0, "battle": 0}.merged(level),
		{"candidate": 0, "seed_index": 0, "battle": 1}.merged(level),
	]
	var tie_ranked := vf.rank_candidates(tied, 0)
	_check(not tie_ranked.is_empty() and int(tie_ranked[0]["candidate"]) == 0,
		"a tie must go to the incumbent (candidate 0), got %s" % str(tie_ranked))


## ARM 5 — the artifact's feature list and its coefficient map agree.
##
## Two lists again. A feature named in one and absent from the other contributes
## zero — the term silently stops existing, and every score stays a perfectly
## well-formed probability.
func _test_every_feature_has_a_coefficient() -> void:
	var vf := RolloutValueFunction.new()
	if not vf.is_loaded():
		_fail("the calibrated artifact did not load")
		return
	var features := vf.features()
	_check(features.size() > 0, "the artifact declares no features")
	for name in features:
		_check(vf.coefficient(name) != 0.0,
			"feature '%s' has no coefficient (or a zero one) in the artifact" % name)
	var calibration := vf.calibration()
	_check(calibration.has("holdout_log_loss"),
		"the artifact carries no held-out log-loss — it cannot say how good it is")
	# ln(2) is the always-predict-the-base-rate model. An artifact that cannot
	# beat a coin flip overall is not calibrated, it is noise with a schema.
	_check(float(calibration.get("holdout_log_loss", 1.0)) < 0.6931,
		"held-out log-loss %.4f does not beat the base-rate model's 0.6931" % [
			float(calibration.get("holdout_log_loss", 1.0))])


## ARM 6 — a terminal verdict STRICTLY dominates every ongoing state, in both
## directions.
##
## 🔴 THIS IS THE ONE PROPERTY THAT LETS A HAND-WRITTEN OBJECTIVE EXIST AT ALL.
## ADR-0253's case for `P(victory)` was that a hand-weighted score needs an
## invented terminal bonus big enough to make winning outrank having more HP, and
## no principled value for it exists. `ProvisionalObjective` does not weight the
## win above an ongoing state — it puts the win OUTSIDE the band an ongoing state
## can reach. Delete the clamp and the argument evaporates while every number
## still looks perfectly well-formed.
func _test_provisional_terminal_verdicts_dominate_every_ongoing_state() -> void:
	var po := ProvisionalObjective.new()
	_check(po.is_loaded(), "the provisional objective has no artifact and should always load")

	# 🔴 THE FIXTURE HAS TO REACH THE CLAMP, AND A "CRUSHING" ONE DOES NOT. A first
	# cut used `_ongoing(1600, 1, 8, 1)` — enemy on one HP and down to one unit —
	# which scores 0.944 and stays under a win with the clamp DELETED, so the seed
	# that removes the clamp went green and this arm proved nothing. The only
	# ongoing record that reaches 1.0 is the SATURATED one: the enemy at zero HP
	# with nobody standing, still flagged ongoing. The kernel latches a verdict
	# before writing that row, which is exactly why the clamp is the only thing
	# standing between it and a tie with a real win.
	var saturated := _ongoing(1600, 0, 8, 0)
	var starved := _ongoing(0, 1600, 0, 8)
	var crushing := _ongoing(1600, 1, 8, 1)
	var hopeless := _ongoing(1, 1600, 1, 8)
	var win := _terminal(GPUBatchSimulator.RESULT_TEAM_0_WINS)
	var loss := _terminal(GPUBatchSimulator.RESULT_TEAM_1_WINS)
	var draw := _terminal(GPUBatchSimulator.RESULT_DRAW)

	_check(po.score(win, 0) > po.score(saturated, 0),
		"a WIN (%.9f) must strictly outrank the SATURATED ongoing state (%.9f) — this is the clamp" % [
			po.score(win, 0), po.score(saturated, 0)])
	_check(po.score(loss, 0) < po.score(starved, 0),
		"a LOSS (%.9f) must strictly underrank the STARVED ongoing state (%.9f) — this is the clamp" % [
			po.score(loss, 0), po.score(starved, 0)])
	_check(po.score(win, 0) > po.score(crushing, 0),
		"a WIN (%.9f) must strictly outrank a crushing ongoing state (%.9f)" % [
			po.score(win, 0), po.score(crushing, 0)])
	_check(po.score(loss, 0) < po.score(hopeless, 0),
		"a LOSS (%.9f) must strictly underrank a hopeless ongoing state (%.9f)" % [
			po.score(loss, 0), po.score(hopeless, 0)])
	_check(is_equal_approx(po.score(draw, 0), 0.5) and is_equal_approx(po.score(draw, 1), 0.5),
		"a mutual wipe is half the objective met from both sides")

	# 🔴 A TERMINAL VERDICT IS A BAND, NOT A POINT — the half of this arm that was
	# MEASURED rather than reasoned. The first cut returned exactly 0.0 for every
	# loss, and instrumented at Gariland the first beat came back with all 64
	# candidates losing: they tied at 0.0 and the beat held by tie-break, while
	# `f` scored the same rows 0.001127 and 0.002705 and could still rank them. An
	# objective flat across lost positions makes the AI stop trying once a battle
	# is decided, which SHORTENS the battle — the exact quantity #1101 exists to
	# measure. So a loss that ground the winner down further must rank above one
	# that did not.
	var lost_cheaply := _latched(GPUBatchSimulator.RESULT_TEAM_0_WINS, 1500)
	var lost_dearly := _latched(GPUBatchSimulator.RESULT_TEAM_0_WINS, 200)
	_check(po.score(lost_dearly, 1) > po.score(lost_cheaply, 1),
		"a LOSS that ground the winner down to 200 HP (%.9f) must rank above one that left them 1500 (%.9f)" % [
			po.score(lost_dearly, 1), po.score(lost_cheaply, 1)])
	_check(po.score(lost_cheaply, 0) > po.score(lost_dearly, 0),
		"and the mirror: the cheaper WIN must rank above the pyrrhic one")
	# The tie-break may never cross the band. Both losses stay under every ongoing
	# state and both wins stay over every one of them.
	for lost in [lost_cheaply, lost_dearly]:
		# `saturated` read from TEAM 1 is the worst ongoing state that exists for
		# team 1 (its mirror), and it is the tight comparison — reading `starved`
		# from team 1 would compare a loss against team 1's BEST position and pass
		# by three orders of magnitude while proving nothing.
		_check(po.score(lost, 1) < po.score(saturated, 1),
			"a terminal loss (%.9f) must stay below the worst ongoing state (%.9f) — the tie-break is inside the band, not across it" % [
				po.score(lost, 1), po.score(saturated, 1)])
		_check(po.score(lost, 0) > po.score(saturated, 0),
			"a terminal win must stay above the best ongoing state — same band")

	# The perspective invariant, which is NOT inherited from the fit: it is a
	# property of both terms being mirrored shares. ADR-0253 dec. 5.
	for row in [saturated, starved, crushing, hopeless, win, loss, draw]:
		var total: float = po.score(row, 0) + po.score(row, 1)
		_check(absf(total - 1.0) <= 1e-9,
			"the provisional objective's perspectives should sum to 1, got %.12f" % total)

	# Monotone in the thing it is named for, in both halves of the sentence.
	_check(po.score(_ongoing(1600, 400, 8, 4), 0) > po.score(_ongoing(1600, 800, 8, 8), 0),
		"killing the enemy must raise the value")
	_check(po.score(_ongoing(1600, 800, 8, 8), 0) > po.score(_ongoing(800, 800, 4, 8), 0),
		"taking casualties must lower the value")
	# HP and standing are two terms because one cannot see the other: same
	# hp_share, four corpses of difference.
	_check(po.score(_ongoing(800, 800, 8, 4), 0) > po.score(_ongoing(800, 800, 4, 8), 0),
		"at equal HP share, the side with more units standing must rank higher")


## ARM 7 — THE CONTROL ARM FOR THE OMISSION. The provisional objective is blind
## to MP and to standoff distance; the fitted one is not, and this arm proves
## BOTH halves against the same two rows.
##
## Without the second half this is a test that an absent term is absent, which is
## nearly vacuous. With it, it is the measurement #1109 rests on: `f` really does
## pay a unit to hoard MP and stand off, so a referee run against `f` would
## measure that instruction rather than the balance.
func _test_provisional_ignores_mp_and_standoff_where_the_fit_does_not() -> void:
	var po := ProvisionalObjective.new()
	var vf := RolloutValueFunction.new()
	if not vf.is_loaded():
		_fail("the fitted artifact did not load — arm 7 cannot run its control half")
		return

	var full_mp := _ongoing(1200, 800, 6, 5)
	var spent_mp := full_mp.duplicate()
	spent_mp["team0_mp"] = 0

	var standing_off := full_mp.duplicate()
	standing_off["team0_engage"] = 200

	_check(is_equal_approx(po.score(full_mp, 0), po.score(spent_mp, 0)),
		"the provisional objective must not price MP (%.9f vs %.9f)" % [
			po.score(full_mp, 0), po.score(spent_mp, 0)])
	_check(is_equal_approx(po.score(full_mp, 0), po.score(standing_off, 0)),
		"the provisional objective must not price standoff distance (%.9f vs %.9f)" % [
			po.score(full_mp, 0), po.score(standing_off, 0)])

	_check(vf.score(full_mp, 0) > vf.score(spent_mp, 0),
		"CONTROL: the fitted f pays for unspent MP — it scored %.6f full and %.6f spent" % [
			vf.score(full_mp, 0), vf.score(spent_mp, 0)])
	_check(vf.score(standing_off, 0) > vf.score(full_mp, 0),
		"CONTROL: the fitted f pays for standing off — it scored %.6f at range and %.6f engaged" % [
			vf.score(standing_off, 0), vf.score(full_mp, 0)])


## ARM 8 — the provisional objective refuses what it cannot score, and in
## particular refuses the record nothing wrote.
##
## 🔴 `RESULT_TEAM_0_WINS == 0`, SO A ZEROED RECORD SPELLS A TEAM-0 WIN. This
## objective is the first thing in the tree to read `result` off a slot that may
## never have been written, and a zero there is a legitimate verdict rather than
## missing data. `stage_victory` writes `tick + 1`, so tick 0 is the tell.
func _test_provisional_refuses_what_it_cannot_score() -> void:
	var po := ProvisionalObjective.new()
	_check(po.score({}, 0) == RolloutObjective.CANNOT_SCORE, "an empty row should refuse")

	var unwritten := _terminal(GPUBatchSimulator.RESULT_TEAM_0_WINS)
	unwritten["ticks"] = 0
	_check(po.score(unwritten, 0) == RolloutObjective.CANNOT_SCORE,
		"a record at tick 0 was never written — its zeroed result must not score as a team-0 win")

	var nonsense := _ongoing(100, 100, 1, 1)
	nonsense["result"] = 99
	_check(po.score(nonsense, 0) == RolloutObjective.CANNOT_SCORE,
		"a result code this kernel never writes should refuse")

	# A refusal must not reach the ranking as a value — it drops the row.
	var rows: Array = [
		{"candidate": 0, "seed_index": 0}.merged(unwritten),
		{"candidate": 1, "seed_index": 0}.merged(_ongoing(1600, 100, 8, 1)),
	]
	var ranked := po.rank_candidates(rows, 0)
	_check(ranked.size() == 1 and int(ranked[0]["candidate"]) == 1,
		"a refused row must be dropped from the ranking, not scored — got %s" % str(ranked))


## ARM 9 — the horizon guard has three states and only ONE of them is silent.
##
## The state this arm exists for is UNCALIBRATED. The guard used to return `true`
## whenever an artifact declared no knee, and a hand-written objective declares
## none by construction — so the guard would have passed, silently, on exactly the
## objective it most needed to say something about.
func _test_horizon_guard_has_three_states_and_only_one_is_silent() -> void:
	var vf := RolloutValueFunction.new()
	if not vf.is_loaded():
		_fail("the fitted artifact did not load — arm 9 cannot check the calibrated states")
		return
	var knee := int(vf.calibration().get("knee_horizon", -1))
	_check(knee > 0, "the fitted artifact declares no knee_horizon, so arm 9 has nothing to compare")

	var agrees: Dictionary = RolloutDriver.check_horizon(vf, knee)
	_check(bool(agrees["agrees"]), "H at the artifact's own knee should agree")
	_check(int(agrees["kind"]) == RolloutObjective.Horizon.CALIBRATED,
		"the fitted objective is calibrated")

	var diverged: Dictionary = RolloutDriver.check_horizon(vf, knee + 1)
	_check(not bool(diverged["agrees"]), "H away from the knee must NOT agree")
	_check(int(diverged["kind"]) == RolloutObjective.Horizon.CALIBRATED,
		"a divergence is still a CALIBRATED verdict — the objective has a knee, the default missed it")

	var uncalibrated: Dictionary = RolloutDriver.check_horizon(ProvisionalObjective.new(), knee)
	_check(not bool(uncalibrated["agrees"]),
		"an uncalibrated objective can vouch for no H at all — it must not report agreement")
	_check(int(uncalibrated["kind"]) == RolloutObjective.Horizon.UNCALIBRATED,
		"the provisional objective's stance is UNCALIBRATED")
	_check(not String(uncalibrated["message"]).is_empty(),
		"the uncalibrated verdict must carry a sentence a run's log can print")


## ARM 10 — the id a run records resolves to an objective, and an unknown one
## does not resolve to a default.
##
## A typo'd `objective_id` that quietly fell back to `f` would produce a corpus
## attributed to an objective that never ran — the whole reason #1109 put the name
## on the interface.
func _test_the_selected_objective_resolves() -> void:
	var selected := RolloutDriver.make_objective(RolloutDriver.objective_id)
	_check(selected != null,
		"RolloutDriver.objective_id is '%s' and nothing answers to it" % RolloutDriver.objective_id)
	if selected != null:
		_check(selected.id() == RolloutDriver.objective_id,
			"the objective resolved from '%s' calls itself '%s'" % [
				RolloutDriver.objective_id, selected.id()])
		_check(selected.is_loaded(), "the selected objective did not load")

	var fitted := RolloutDriver.make_objective(RolloutValueFunction.DEFAULT_ID)
	_check(fitted != null and fitted.id() == RolloutValueFunction.DEFAULT_ID,
		"the fitted objective must stay reachable by name — the refit is what flips the default back")

	_check(RolloutDriver.make_objective("no-such-objective") == null,
		"an unknown id must refuse rather than fall back to a default")


## A result record for an ONGOING battle, carrying every field BOTH objectives
## read so one row can be handed to either.
func _ongoing(hp0: int, hp1: int, alive0: int, alive1: int) -> Dictionary:
	var row := _record(hp0, hp1, alive0, alive1)
	row["result"] = GPUBatchSimulator.RESULT_ONGOING
	row["ticks"] = 400
	return row


## A record whose battle has LATCHED. Its HP and standing counts are deliberately
## level, so anything that outranks it did so on the verdict alone.
func _terminal(verdict: int) -> Dictionary:
	var row := _record(800, 800, 4, 4)
	row["result"] = verdict
	row["ticks"] = 400
	return row


## A latched battle where the WINNER came out on `winner_hp` of their 1600 pool —
## the input the terminal tie-break reads. The loser is at 0, as a latched battle
## always leaves them.
func _latched(verdict: int, winner_hp: int) -> Dictionary:
	var row := _record(winner_hp, 0, 4, 0) if verdict == GPUBatchSimulator.RESULT_TEAM_0_WINS \
		else _record(0, winner_hp, 0, 4)
	row["result"] = verdict
	row["ticks"] = 400
	return row


func _record(hp0: int, hp1: int, alive0: int, alive1: int) -> Dictionary:
	return {
		"team0_hp": hp0, "team1_hp": hp1,
		"team0_max_hp": 1600, "team1_max_hp": 1600,
		"team0_alive": alive0, "team1_alive": alive1,
		"team0_mp": 400, "team1_mp": 400,
		"team0_max_mp": 800, "team1_max_mp": 800,
		"team0_engage": 20, "team1_engage": 20,
	}


func _load_cases() -> Array:
	if not FileAccess.file_exists(FIXTURE):
		_fail("no fixture at %s" % FIXTURE)
		return []
	var parsed: Variant = JSON.parse_string(FileAccess.get_file_as_string(FIXTURE))
	if typeof(parsed) != TYPE_DICTIONARY:
		_fail("%s is not a JSON object" % FIXTURE)
		return []
	return (parsed as Dictionary).get("cases", [])
