extends RefCounted

## Animation resolution map — per-activity resolution functions (ADR-0021,
## ADR-0024). The class name matches the CONTEXT.md cluster term; "atlas"
## the historical name retired so it can mean SHP/SPR sheets without
## ambiguity.
##
## Each public `resolve_*` function takes the circumstances relevant to a
## given activity and returns a Resolution describing which BODY / WEP1 /
## EFF1 slots to play, plus a source verdict the viewer reads to show
## "atlas hit" vs "miss" verdicts.
##
## Two kinds of resolvers:
##
##   - **state_animations.json-backed** (most states) — load the per-sprite-type
##     {front, back} pair from the JSON and return it. Slot `1` is treated as
##     a stub (no real animation for this sprite type) → returns MISS rather
##     than silently routing to TYPE1's slot (the TYPE1-fallback bug ADR-0021
##     retires).
##
##   - **equipment-driven** (ATTACKING today, BLOCKING / SPELL_CASTING later)
##     — read equipment / ability / modifier inputs to pick the slot. Mirrors
##     the per-state-resolution-shape principle from ADR-0021.
## Vault: [[Scenario 6 Ride Off]]
## Vault: [[Sprite Cardinal Pose Selection]]
## Vault: [[Unit Anim Opcode]]

# ADR-0223 dec. 8 — this line USED to name `JsonAsset` where `src/data/`
# declared it, which is ARM7_BURN_DOWN #809 and goal #5 unmet on the TYPE
# axis. The file moved to the port; naming the port is what a portable addon
# is ALLOWED to do (ADR-0139 dec. 12, `plugin.cfg` `deps=`), and the spelling
# below is unchanged (ADR-0212 dec. 1).
const JsonAsset = ExMateriaPlatform.JsonAsset

# ADR-0212 dec. 1 — the class is INTERNAL to this addon: no global `class_name`,
# so an in-addon consumer preloads the file it wants.
const WeaponAnimationSelector = preload("res://addons/exmateria_sprite_rig/layers/WeaponAnimationSelector.gd")
const DisplayActivity = preload("res://addons/exmateria_sprite_rig/state/DisplayActivity.gd")

## `ContentPort` is `addons/exmateria_sprite_rig`'s, published on the addon's one
## global name; this aliases it back so the call sites below stay a verb rather
## than a façade walk (ADR-0211 dec. 4, ADR-0217 dec. 9). The port replaces a
## direct name for a host content store: this file no longer compiles against one.
const ContentPort = ExMateriaSpriteRig.ContentPort


class Resolution:
	extends RefCounted

	## FFT anim_id the body layer dispatches on (ADR-0053). `0` = idle
	## (pose-octant LUT branch). `1..0x1f4` = SEQ-range, slot derived as
	## `(anim_id-1)*2 + cardinal_offset` at paint time. `>= 0x1f5` = EVTCHR
	## (deferred). `-1` = no body anim resolved (MISS — caller should skip).
	var body_slot: int = -1
	var wep1_slot: int = -1       ## WEP1 layer SEQ slot id; -1 = no weapon layer
	var eff1_slot: int = -1       ## EFF1 layer SEQ slot id; -1 = no effect layer
	var source: String = "miss"   ## "atlas" | "miss"
	var note: String = ""         ## human-readable explanation for the viewer readout

	func _to_string() -> String:
		return "Resolution(body=%d, wep1=%d, eff1=%d, source=%s, note=%s)" % [
			body_slot, wep1_slot, eff1_slot, source, note]


# ---------------------------------------------------------------------------
# Asset caches (loaded lazily, shared across resolvers).
#
# State-animations data is now the hand-authored Resource at
# `addons/exmateria_sprite_rig/resources/map.tres`, edited in the Godot Inspector
# (see ResourceHotReload for the file-mtime watcher that swaps `_resource`
# when it changes on disk). weapon_animation_ids.json stays JSON — it's
# ROM-derived, regenerated by `tools/parse_weapon_animation_ids.py`.
# ---------------------------------------------------------------------------

## The three resource classes stopped being global `class_name`s in #744 -- a boot
## proved map.tres loads without them. Aliased back so the annotations below stay
## spelled the way they were (ADR-0211 dec. 4).
const AnimationResolutionMapResource = preload("res://addons/exmateria_sprite_rig/resources/AnimationResolutionMapResource.gd")
const SpriteTypeResource = preload("res://addons/exmateria_sprite_rig/resources/SpriteTypeResource.gd")
const ActivityRowResource = preload("res://addons/exmateria_sprite_rig/resources/ActivityRowResource.gd")

const MAP_RESOURCE_PATH := "res://addons/exmateria_sprite_rig/resources/map.tres"
const _WEAPON_ANIM_IDS_PATH := "res://addons/exmateria_sprite_rig/resources/weapon_animation_ids.json"

static var _resource: AnimationResolutionMapResource = null
static var _weapon_anim_ids: Dictionary = {}
static var _loaded: bool = false


static func _ensure_loaded() -> void:
	if _loaded:
		return
	_resource = load(MAP_RESOURCE_PATH) as AnimationResolutionMapResource
	if _resource == null:
		push_warning("[AnimationResolutionMap] missing or invalid Resource at %s" % MAP_RESOURCE_PATH)
	_weapon_anim_ids = JsonAsset.load_dict(_WEAPON_ANIM_IDS_PATH)
	_loaded = true


## Swap the cached Resource — called by ResourceHotReload after a file-mtime
## change. Callers should then re-fire their current activity to repaint
## with the freshly-loaded routing.
static func set_resource(new_res: AnimationResolutionMapResource) -> void:
	_resource = new_res


## Look up a state's {front, back} pair for the given sprite_type. Returns
## explicit MISS for absent states OR slot-1 stub entries — no TYPE1
## fallback (ADR-0021 retires the StateAnimationDatabase.gd:75-78 fallback).
##
## Path D (ADR-0053): the returned `body_slot` is now the FFT anim_id the
## renderer dispatches on, not the authored SEQ slot. IDLE collapses to
## `anim_id 0` (pose-octant LUT idle branch); other activities invert the
## SEQ-range formula `slot = (anim_id-1)*2`, so `anim_id = front/2 + 1`.
## The `use_back` arg is now dead (renderer derives front/back at paint
## time from `current_anim_id` + cardinal_idx); kept on the signature so
## existing callers stay valid until they're cleaned up.
static func _resolve_state_for_type(sprite_type: String, state_name: String, _use_back: bool, cinematic_idle: bool = false) -> Resolution:
	_ensure_loaded()
	var r := Resolution.new()
	if _resource == null:
		r.note = "%s — animation resolution map Resource not loaded" % state_name
		return r
	var st: SpriteTypeResource = _resource.find_sprite_type(sprite_type)
	if st == null:
		r.note = "%s — no entry for sprite_type=%s in map.tres" % [state_name, sprite_type]
		return r
	var row: ActivityRowResource = st.find_row(state_name)
	if row == null:
		r.note = "%s — no row for sprite_type=%s, activity=%s in map.tres" % [state_name, sprite_type, state_name]
		return r
	# Slot 1 is the hand-authored "no real animation" stub (per the original
	# JSON convention; preserved in the Resource form). Surface as MISS so the
	# viewer flags the gap rather than playing the wrong slot.
	if row.front == 1 or row.front < 0:
		r.note = "%s — sprite_type=%s has stub slot 1 (no real animation authored)" % [state_name, sprite_type]
		return r
	# Path D anim_id derivation. Two distinct "idle" animations exist:
	#   * CINEMATIC idle — scenario VM units (which carry a precise facing_angle)
	#     collapse to anim_id 0 so the renderer takes the pose-octant TENT
	#     (Sub-tables A+B): the chapel "at-ease" rotating stance authored at
	#     SEQ keys 1..5.
	#   * COMBAT / gameplay idle — units with no precise angle resolve to their
	#     real idle SEQ (front 6 -> anim_id 4) and ride the SEQ-range
	#     cardinal-collapse path (Sub-tables E+F), painting the authored
	#     standing/breathing idle (SEQ 6/7) at one of the 4 cardinals.
	# Routing combat idle through the tent (the pre-fix behavior) broke it:
	# MON/RUKA/KANZEN/ARUTE have no SEQ keys 1/3/4 (idle silently unpainted) and
	# the humanoid types render the wrong pose. The `cinematic_idle` flag is the
	# discriminator (Unit passes facing_angle >= 0). See ADR-0053.
	if cinematic_idle and (state_name == "IDLE" or state_name == "IDLE_LOW_HEALTH"):
		r.body_slot = 0
	else:
		r.body_slot = (row.front / 2) + 1
	r.source = "atlas"
	r.note = "%s @ sprite_type=%s → BODY anim_id %d (map.tres front=%d)" % [
		state_name, sprite_type, r.body_slot, row.front]
	return r


# ---------------------------------------------------------------------------
# State-driven resolvers (no equipment dependency). All read from
# map.tres (Inspector-edited Resource) via _resolve_state_for_type.
# ---------------------------------------------------------------------------

static func resolve_idle(sprite_type: String, use_back: bool, cinematic_idle: bool = false) -> Resolution:
	return _resolve_state_for_type(sprite_type, "IDLE", use_back, cinematic_idle)

static func resolve_idle_low_health(sprite_type: String, use_back: bool, cinematic_idle: bool = false) -> Resolution:
	return _resolve_state_for_type(sprite_type, "IDLE_LOW_HEALTH", use_back, cinematic_idle)

static func resolve_walking(sprite_type: String, use_back: bool) -> Resolution:
	# Single ground-traversal animation; walk vs. run is a playback-speed
	# knob owned by `_get_unit_anim_speed` in CombatLoop, keyed off the GPU
	# state — there is no separate RUNNING activity.
	return _resolve_state_for_type(sprite_type, "WALKING", use_back)

static func resolve_jumping(sprite_type: String, use_back: bool) -> Resolution:
	return _resolve_state_for_type(sprite_type, "JUMPING", use_back)

static func resolve_landing(sprite_type: String, use_back: bool) -> Resolution:
	return _resolve_state_for_type(sprite_type, "LANDING", use_back)

static func resolve_using_item(sprite_type: String, use_back: bool) -> Resolution:
	return _resolve_state_for_type(sprite_type, "USING_ITEM", use_back)

static func resolve_dying(sprite_type: String, use_back: bool) -> Resolution:
	return _resolve_state_for_type(sprite_type, "DYING", use_back)

static func resolve_dead(sprite_type: String, use_back: bool) -> Resolution:
	# Same slot as DYING by data; playback holds the final frame for the corpse pose.
	return _resolve_state_for_type(sprite_type, "DEAD", use_back)

static func resolve_getting_up(sprite_type: String, use_back: bool) -> Resolution:
	return _resolve_state_for_type(sprite_type, "GETTING_UP", use_back)

static func resolve_celebrating(sprite_type: String, use_back: bool) -> Resolution:
	# Victory dance (ADR-0026). FFT has no dedicated victory SEQ, so the
	# celebration reuses the per-sprite-type Dancing pose authored in map.tres
	# (TYPE1/TYPE3 → 82/83). Non-humanoid types are intentionally unauthored →
	# explicit MISS (ADR-0021), never a TYPE1-as-base fallback.
	return _resolve_state_for_type(sprite_type, "CELEBRATING", use_back)

static func resolve_awaiting_impact(sprite_type: String, use_back: bool) -> Resolution:
	# Firer is waiting for an in-flight projectile to land (ADR-0032). Every
	# sprite-type row points at the unit's IDLE SEQ pair today, so the firer
	# visually returns to neutral while the bullet crosses. Separate row so
	# the binding can deviate later without touching IDLE.
	return _resolve_state_for_type(sprite_type, "AWAITING_IMPACT", use_back)


## Dispatcher for **parameterless** activities — used by Unit.update_animation()
## so the legacy `anim_state.get_state_anim_pair` path retires and the resolver
## becomes the single authority for IDLE/WALKING/etc. as well as the
## parameterized cases the semantic Unit methods drive.
##
## Parameterized activities (ATTACKING / SPELL_CASTING / SPELL_CHARGING) return
## MISS here — callers must use `unit.attack(vertical)` /
## `unit.cast_spell(ability_id)` / `unit.charge_ability(ability_id)` so the
## extra inputs are wired through.
##
## IDLE auto-picks the IDLE_LOW_HEALTH variant when `low_health` is true (caller
## precomputes `hp < max_hp / 4` per the FFT AutoPotion threshold). Passing
## A.IDLE_LOW_HEALTH directly still works for explicit overrides (e.g. the
## animation viewer dropdown) — the variant pick is the resolver's job only
## when the caller hands it the base IDLE Display value.
static func resolve_for_activity(activity: DisplayActivity.Activity, sprite_type: String, use_back: bool, low_health: bool = false, cinematic_idle: bool = false) -> Resolution:
	var A := DisplayActivity.Activity
	match activity:
		A.IDLE:
			if low_health:
				return resolve_idle_low_health(sprite_type, use_back, cinematic_idle)
			return resolve_idle(sprite_type, use_back, cinematic_idle)
		A.IDLE_LOW_HEALTH:         return resolve_idle_low_health(sprite_type, use_back, cinematic_idle)
		A.WALKING:                 return resolve_walking(sprite_type, use_back)
		A.JUMPING:                 return resolve_jumping(sprite_type, use_back)
		A.LANDING:                 return resolve_landing(sprite_type, use_back)
		A.USING_ITEM:              return resolve_using_item(sprite_type, use_back)
		A.DYING:                   return resolve_dying(sprite_type, use_back)
		A.DEAD:                    return resolve_dead(sprite_type, use_back)
		A.GETTING_UP:              return resolve_getting_up(sprite_type, use_back)
		A.CELEBRATING:             return resolve_celebrating(sprite_type, use_back)
		A.AWAITING_IMPACT:         return resolve_awaiting_impact(sprite_type, use_back)
		A.ATTACKING, A.SPELL_CASTING, A.SPELL_CHARGING:
			# Parameterized — caller MUST use the semantic Unit method.
			var r := Resolution.new()
			r.note = "activity is parameterized — use unit.attack/cast_spell/charge_ability"
			return r
		_:
			return resolve_unimplemented("activity_%d" % int(activity))


# ---------------------------------------------------------------------------
# Equipment-driven resolvers.
# ---------------------------------------------------------------------------

## ATTACKING resolution. Per-sprite-type dispatch (ADR-0021 step 2).
##
## Humanoid sprite types (TYPE1 and TYPE3 — TYPE3 is the SEQ TYPE2 sprites
## load, not a separate body shape) use the weapon-driven palette: BODY base
## picked by item_type_id, plus a parallel WEP1 layer animation. To be
## ROM-data-driven (parse `weapon_animation_ids` from BATTLE.BIN) per
## ADR-0021 step 3.
##
## Non-humanoid sprite types (MON / CYOKO / RUKA / ARUTE / KANZEN / OTHER)
## attack with their *natural weapon* — beak, claws, etc. The item_type_id
## is IGNORED for them; they have no WEAPON layer (the wiki table at
## research/wiki_articles/target_reaction_animations.txt confirms: weapon /
## effect columns are N/A for non-humanoid sprite types). Slots come from
## animation_names.json — see comments per branch below.
##
## Args:
##   sprite_type: from Unit.get_seq_type() — "TYPE1" / "TYPE3" / "MON" / …
##   item_type_id: ItemDatabase item type id (0=Unarmed, 10=Gun, 11/12=Bow, …)
##   vertical: 0=HIGH, 1=MID, 2=LOW (WeaponAnimationSelector.VerticalAngle)
##   use_back: camera-relative facing — true if the unit's back is to camera
static func resolve_attack(sprite_type: String, item_type_id: int, vertical: int, _use_back: bool) -> Resolution:
	var r := Resolution.new()
	var key := sprite_type.to_lower()

	# Humanoid path: BODY slot from ROM-parsed weapon_animation_ids.json
	# (per-item-type {high, mid, low}); WEP1 base from the per-category mapping
	# (a separate convention not stored in the same ROM table — see WEP1 note).
	if key == "type1" or key == "type3":
		_ensure_loaded()
		var entry: Dictionary = _weapon_anim_ids.get(str(item_type_id), {})
		if entry.is_empty():
			r.note = "ATTACKING item_type=%d not in weapon_animation_ids.json (typical: thrown items 32-34 use a separate animation flow)" % item_type_id
			return r
		var heights: Array[int] = [int(entry.get("high", 0)), int(entry.get("mid", 0)), int(entry.get("low", 0))]
		var body_chosen: int = heights[vertical]
		# Slot 0 in this table means "no attack" — Shield is the canonical case
		# (item_type 19 reads as 0/0/0, since shields don't attack).
		if body_chosen == 0:
			r.note = "ATTACKING with %s (item_type=%d): ROM table reads slot 0 (no attack animation — typical for Shield)" % [String(entry.get("name", "?")), item_type_id]
			return r
		# Path D: convert weapon-table SEQ slot to anim_id (renderer derives
		# front/back from cardinal_idx, not from the writer-side facing pick).
		r.body_slot = (body_chosen / 2) + 1
		# WEP1 slot delegated to WeaponAnimationSelector, which owns the
		# per-category metadata (CATEGORY_BASE + HAS_HEIGHT_VARIANTS):
		#   - SWING/GUN/BOW/POKE/THROW use HIGH/MID/LOW height variants
		#   - INSTRUMENT/BOOK/SHIELD use front/back only (no height)
		# Unarmed (item_type 0) and Shield (item_type 19) intentionally hide the
		# WEP1 layer — Unarmed because the BODY pose already shows the fist;
		# Shield because the BODY path returns MISS (no attack).
		if item_type_id == 0:
			# No weapon layer; the BODY pose holds the fist visual.
			pass
		else:
			r.wep1_slot = WeaponAnimationSelector.get_wep_animation_id(item_type_id, vertical, _use_back)
		r.note = "ATTACKING with %s (item_type=%d) — BODY from ROM weapon_animation_ids; WEP1 from WeaponAnimationSelector" % [String(entry.get("name", "?")), item_type_id]
		r.source = "atlas"
		return r

	# Non-humanoid path: fixed natural-attack slot (per type's animation_names),
	# no WEP1, item_type_id ignored. The slot table per sprite type, [HIGH, MID, LOW]:
	var body_base: int = -1
	match key:
		"mon":
			# animation_names: 124 Attack High, 126 Attack Low (no Mid — reuse High).
			body_base = [124, 124, 126][vertical]
			r.note = "MON natural attack (item ignored; no Mid in data — reuses High)"
		"cyoko":
			# animation_names: 122/124/126 Beak High/Mid/Low.
			body_base = [122, 124, 126][vertical]
			r.note = "Chocobo Beak (item ignored)"
		"ruka":
			# Same structure as MON — RUKA shares MON.SHP.
			body_base = [124, 124, 126][vertical]
			r.note = "Lucavi natural attack (item ignored; no Mid in data)"
		"arute":
			# animation_names: 122/124/126 Attack High/Mid/Low.
			body_base = [122, 124, 126][vertical]
			r.note = "Altima first form attack (item ignored)"
		"kanzen":
			# animation_names: 122 High, 124 Mid; no Low — reuse Mid.
			body_base = [122, 124, 124][vertical]
			r.note = "Altima perfect form attack (item ignored; no Low in data)"
		_:
			# OTHER and unknowns: no labeled attack slot — return MISS.
			r.note = "%s — no atlas attack mapping (no labeled attack slot in animation_names.json)" % sprite_type
			return r

	# Path D: convert natural-attack SEQ base to anim_id; renderer adds the
	# cardinal_idx offset at paint time via Sub-table E.
	r.body_slot = (body_base / 2) + 1
	r.source = "atlas"
	return r


# ---------------------------------------------------------------------------
# Ability-driven resolvers.
# ---------------------------------------------------------------------------

## SPELL_CASTING resolution. The slot is per-ability: `effect_anim_id * 2`
## (from the ability data table, populated for 416/512 abilities). For
## Cure / Raise / most basic spells effect_anim_id = 44 → slot 88. When
## ability_id is invalid or effect_anim_id == 0, falls back to the
## per-sprite-type SPELL_CASTING slot from state_animations.json.
##
## Per the wiki finding (research/wiki_articles/casting_animation_selection.txt),
## FFT drives ONE cast animation per ability from the BATTLE.BIN 0x2CE10
## table — no separate two-handed branch. The PSX engine doesn't distinguish
## one-handed vs. two-handed cast at the ROM level.
static func resolve_spell_casting(sprite_type: String, ability_id: int, use_back: bool) -> Resolution:
	var anim_id: int = _ability_effect_anim_id(ability_id)
	if anim_id > 0:
		var r := Resolution.new()
		# Path D: was `slot = effect_anim_id*2 + offset`. Anim_id =
		# `slot/2 + 1` = `effect_anim_id + 1`.
		r.body_slot = anim_id + 1
		r.source = "atlas"
		r.note = "SPELL_CASTING ability_id=%d → effect_anim_id %d → anim_id %d" % [ability_id, anim_id, r.body_slot]
		return r
	# Fall back to per-sprite-type default
	var fallback := _resolve_state_for_type(sprite_type, "SPELL_CASTING", use_back)
	if fallback.source == "atlas":
		fallback.note = "SPELL_CASTING fallback (ability_id=%d has no effect_anim_id) → %s" % [ability_id, fallback.note]
	return fallback


## SPELL_CHARGING — per-sprite-type slot for v0. The ability-specific
## charging pose lives in BATTLE.BIN at 0x2CDE8 (charging_pose_set_id →
## {start, sustain} pair); parsing that is a future step.
##
## Per the wiki finding, FFT drives ONE charging animation per ability —
## the charging_pose_set_id covers Sing / Dance / Jump / Crouch / Spell-cast
## / Summon / Kneeling poses inside that single axis. No ROM branch for
## "spell vs ability" charging.
static func resolve_spell_charging(sprite_type: String, ability_id: int, use_back: bool) -> Resolution:
	var r: Resolution = _resolve_state_for_type(sprite_type, "SPELL_CHARGING", use_back)
	if r.source == "atlas" and ability_id >= 0:
		r.note = "SPELL_CHARGING (per-sprite default; ability-specific charging_pose_set_id requires BATTLE.BIN 0x2CDE8 table — future step)"
	return r


# Helpers
## `-1` for a negative id or one that names no ability; `0` for an ability
## that HAS no cast animation. The caller branches on `> 0`, so both fall
## back — but only one of them is a bad id, and the port keeps them apart.
static func _ability_effect_anim_id(ability_id: int) -> int:
	return ContentPort.ability_effect_anim_id(ability_id)


# ---------------------------------------------------------------------------
# Catch-all for activities the resolver doesn't yet handle. The ADR-0021
# audit retired DAMAGED / BUFFED / DEBUFFED (now React-only via
# react_playback), ARMS_RAISE (ambiguous, never wired), and WAITING (input
# dimension, not a state) — so this branch fires only for genuinely new,
# unimplemented activities.
# ---------------------------------------------------------------------------

static func resolve_unimplemented(state_name: String) -> Resolution:
	var r := Resolution.new()
	r.note = "%s — no atlas resolver yet (TODO; see ADR-0021 migration order)" % state_name
	return r
