extends RefCounted
## GENERATED — do not edit. Regenerate with:
##   uv run python tools/generate_feds_instrument_names.py
## Source of truth: fft-plugin/src/fft_instrument_picker_generated.inc (the DAW
## instrument picker table, itself generated from fft-plugin/data CSVs).
##
## Names for the FEDS Instrument opcode (0xAC) raw ids — waveset samples. First
## picker row per id wins (later rows are variant-group aliases). Drift guard:
## tools/test_feds_instrument_names_drift.py. No class_name (ADR-0004).

const NAMES := {
	0: "Heavy Square Wave (F-4) · Synth",
	1: "Empty/Silent · Silence",
	2: "Telephone (A#-3) · SFX",
	3: "Fat Saw Wave-Asp (F-4) · Synth",
	4: "Heavy Square Wave (F-4) · Synth",
	5: "Fat Saw Wave-Asp (F-5) · Synth",
	6: "Heavy Square Wave (F-5) · Synth",
	7: "Tuba (C-3) · Brass",
	8: "Glockenspiel (A-3) · Bell/Perc",
	9: "Bright Beep (C-3) · SFX",
	10: "Seashore (C-2) · Ambient",
	11: "Seashore (C-3) · Ambient",
	12: "Seashore (C-4) · Ambient",
	13: "Drum Hit + Seashore (C-3) · Percussion",
	14: "Telephone 2 (C-5) · SFX",
	15: "Explosion (C-2) · SFX",
	16: "Cymbal (A-3, Orchestra Kit) · Percussion",
	17: "Telephone 2 (C-7) · SFX",
	18: "Tubular Bells (C-5) · Bell/Perc",
	19: "Slap Bass 2 (C-1) · Bass",
	20: "Slap Bass 2 (C-2) · Bass",
	21: "Slap Bass 2 (C-3) · Bass",
	22: "Slap Bass 2 (C-4) · Bass",
	23: "Slap Bass 2 (C-5) · Bass",
	24: "Trumpet (C-3) · Brass",
	25: "Trumpet (C-4) · Brass",
	26: "Pizzicato Strings (C-3) · Strings",
	27: "Vibraslap/Spinner (A#-3, Orchestra Kit) · Percussion",
	28: "Bassoon (C-3) · Woodwind",
	29: "Bassoon (C-4) · Woodwind",
	30: "Bassoon (C-5) · Woodwind",
	31: "Machine Gun (C-5) · SFX",
	32: "Synth Strings (C-2) · Strings",
	33: "Synth Strings (C-4) · Strings",
	34: "Synth Strings (C-4) · Strings",
	35: "Synth Strings (C-5) · Strings",
	36: "Synth Strings (C-6) · Strings",
	37: "Synth Strings (C-7) · Strings",
	38: "Fretless Bass (C-2) · Bass",
	39: "Fretless Bass (C-3) · Bass",
	40: "Fretless Bass (C-4) · Bass",
	41: "Fretless Bass (C-5) · Bass",
	42: "Fretless Bass (C-6) · Bass",
	43: "Tuba (C-1) · Brass",
	44: "Tuba (C-2) · Brass",
	45: "Empty · Silence",
	46: "Bassoon (C-4) · Woodwind",
	47: "Bassoon (C-5) · Woodwind",
	48: "Trombone (C-2) · Brass",
	49: "Trombone (C-3) · Brass",
	50: "Trombone (C-4) · Brass",
	51: "Synth Brass 1, Modulated (C-3) · Brass",
	52: "Synth Brass 1, Modulated (C-4) · Brass",
	53: "Synth Brass 1, Modulated (C-5) · Brass",
	54: "Empty · Silence",
	55: "Empty · Silence",
	56: "Empty · Silence",
	57: "Cymbal Hit (A-3, Orchestra Kit) · Percussion",
	58: "Cymbal Hit (B-3, Orchestra Kit) · Percussion",
	59: "Vibraphone (C-3) · Bell/Perc",
	60: "French Horns (C-2) · Brass",
	61: "French Horns (C-3) · Brass",
	62: "French Horns (C-4) · Brass",
	63: "French Horns (C-5) · Brass",
	64: "Timpani (C-3) · Percussion",
	65: "Pizzicato (C-4) · Strings",
	66: "Timpani (C-2) · Percussion",
	67: "Tubular Bells (C-5) · Bell/Perc",
	68: "Clarinet (C-3) · Woodwind",
	69: "Empty · Silence",
	70: "Clarinet (C-4) · Woodwind",
	71: "Clarinet (C-5) · Woodwind",
	72: "Brush (A-4, Orchestra Kit) · Percussion",
	73: "Cymbal (A-3, Orchestra Kit) · Percussion",
	74: "French Horns (C-3) · Brass",
	75: "French Horns (C-4) · Brass",
	76: "French Horns (C-5) · Brass",
	77: "French Horns (C-6) · Brass",
	78: "French Horns (C-7) · Brass",
	79: "Trombone (C-1) · Brass",
	80: "Trombone (C-2) · Brass",
	81: "Trombone (C-3) · Brass",
	82: "Trombone (C-4) · Brass",
	83: "Trombone (C-5) · Brass",
	84: "Synth Strings (C-2) · Strings",
	85: "Synth Strings (C-3) · Strings",
	86: "Synth Strings (C-4) · Strings",
	87: "Synth Strings (C-5) · Strings",
	88: "Synth Strings (C-6) · Strings",
	89: "Synth Strings (C-7) · Strings",
	90: "Synth Strings 1 (C-2) · Strings",
	91: "Synth Strings 1 (C-3) · Strings",
	92: "Synth Strings 1 (C-4) · Strings",
	93: "Synth Strings 1 (C-5) · Strings",
	94: "Synth Strings 1 (C-6) · Strings",
	95: "Synth Strings 2 (C-2) · Strings",
	96: "Synth Strings 2 (C-3) · Strings",
	97: "Synth Strings 2 (C-4) · Strings",
	98: "Synth Strings 2 (C-5) · Strings",
	99: "Snare Hit (E-2, Orchestra Kit) · Percussion",
	100: "Synth Strings 1 (C-5) · Strings",
	101: "Tubular Bells (C-6) · Bell/Perc",
	102: "Bass Drum Hit (F-2, Orchestra Kit) · Percussion",
	103: "Empty · Silence",
	104: "Empty · Silence",
	105: "High-Frequency Noise · SFX/Noise",
	106: "High-Pitched Strings · Strings",
	107: "Sub-Bass Horn · Brass",
	108: "Bass Horn · Brass",
	109: "Horn · Brass",
	110: "Treble Horn · Brass",
	111: "Above-Treble Horn · Brass",
	112: "Oscillating Static · SFX/Noise",
	113: "Percussive Hammer · Percussion",
	114: "Sustained Oscillating Bass Noise · SFX/Noise",
	115: "Low Percussive Hammer · Percussion",
	116: "High-Frequency Oscillating Voice · Voice",
	117: "Metal Percussive Strike · Percussion",
	118: "Wide Signal · Synth",
	119: "Pitched-Up Wide Signal · Synth",
	120: "Sub-Bass Horn · Brass",
	121: "Bass Horn · Brass",
	122: "Horn · Brass",
	123: "Treble Horn · Brass",
	124: "Above-Treble Horn · Brass",
	125: "Bass Tone · Synth",
	126: "Pitched-Up Bass Tone · Synth",
	127: "Wide Sub-Bass Tone · Synth",
	128: "Wide Bass Tone · Synth",
	129: "Wide Tone · Synth",
	130: "Ambient High-Frequency Voice · Voice",
	131: "High-Pitched Bell · Bell/Perc",
	132: "Ambient Voice · Voice",
	133: "Error Tone · SFX",
	134: "High-Frequency Tone · Synth",
	135: "Loud High-Frequency Tone · Synth",
	136: "Ambient High-Frequency Oscillating Tone · Synth",
	137: "Pitched-Up Ambient HF Oscillating Tone · Synth",
	138: "Drum Roll · Percussion",
	139: "Bright Ambient Voice · Voice",
	140: "Cymbal Crashing · Percussion",
	141: "Tremolo Noise · SFX/Noise",
	142: "Deep Ambient Voice · Voice",
	143: "Sub-Bass String · Strings",
	144: "Bass String · Strings",
	145: "String · Strings",
	146: "Treble String · Strings",
	147: "Above-Treble String · Strings",
	148: "High-Pitched String · Strings",
	149: "Wide Sub-Bass String · Strings",
	150: "Wide Bass String · Strings",
	151: "Wide String · Strings",
	152: "Wide Treble String · Strings",
	153: "Wide Above-Treble String · Strings",
	154: "Wide High-Pitched String · Strings",
	155: "Bass Vibrato String · Strings",
	156: "Vibrato String · Strings",
	157: "Treble Vibrato String · Strings",
	158: "Above-Treble Vibrato String · Strings",
	159: "High-Pitched Vibrato String · Strings",
	160: "Bass String (Duplicate of 161) · Strings",
	161: "Bass String · Strings",
	162: "Treble String · Strings",
	163: "Above-Treble String · Strings",
	164: "Bass String · Strings",
	165: "String · Strings",
	166: "Above-Treble String · Strings",
	167: "Treble Bell (Envelope Close) · Bell/Perc",
	168: "Above-Treble Voice · Voice",
	169: "Bell (Envelope Close) · Bell/Perc",
	170: "Staccato Bell · Bell/Perc",
	171: "Bell (Envelope Close) · Bell/Perc",
	172: "Bass Muted Horn · Brass",
	173: "Muted Horn · Brass",
	174: "Treble Muted Horn · Brass",
	175: "Above-Treble Muted Horn · Brass",
	176: "Static Clip Hit/slap sound · SFX",
	177: "Clipped Thump · SFX",
	178: "Inaudible Clip · Silence",
	179: "Nearly Inaudible Clip · Silence",
	180: "Blip · SFX",
	181: "Empty · Silence",
	182: "Empty · Silence",
	183: "Empty · Silence",
	184: "Clip · SFX",
	185: "Empty · Silence",
	186: "Empty · Silence",
	187: "Empty · Silence",
	188: "Empty · Silence",
	189: "Blip · SFX",
	190: "Nearly Inaudible Clip · Silence",
	191: "Empty · Silence",
	192: "Empty · Silence",
	193: "Empty · Silence",
	194: "Empty · Silence",
	195: "Nearly Inaudible Clip · Silence",
	196: "Blip · SFX",
	197: "Empty · Silence",
	198: "Empty · Silence",
	199: "Empty · Silence",
	200: "Empty · Silence",
	201: "Empty · Silence",
	202: "Empty · Silence",
	203: "Empty · Silence",
	204: "Empty · Silence",
	205: "Empty · Silence",
	206: "Empty · Silence",
	207: "Empty · Silence",
	208: "Empty · Silence",
	209: "Empty · Silence",
	210: "Empty · Silence",
	211: "Blip · SFX",
	212: "Nearly Inaudible Clip · Silence",
	213: "Empty · Silence",
	214: "Pop · SFX",
	215: "Empty · Silence",
	216: "Pop · SFX",
	217: "Pop · SFX",
	218: "Pop · SFX",
	219: "Empty · Silence",
	220: "Empty · Silence",
	221: "Empty · Silence",
	222: "Empty · Silence",
	223: "Empty · Silence",
	224: "Empty · Silence",
	225: "Empty · Silence",
	226: "Empty · Silence",
	227: "Empty · Silence",
	228: "Empty · Silence",
	229: "Empty · Silence",
	230: "Empty · Silence",
	231: "Empty · Silence",
	232: "Empty · Silence",
	233: "Empty · Silence",
	234: "Pop · SFX",
	235: "Empty · Silence",
	236: "Inaudible Clip · Silence",
	237: "Bell · Bell/Perc",
	238: "Empty · Silence",
	239: "Pop · SFX",
	240: "Static + Bass String · Strings/Noise",
	241: "Empty · Silence",
	242: "Empty · Silence",
	243: "Bell (Envelope Close) · Bell/Perc",
	244: "Nearly Inaudible Clip · Silence",
	245: "Empty · Silence",
	246: "Pop · SFX",
	247: "Nearly Inaudible Clip · Silence",
	248: "Nearly Inaudible Clip · Silence",
	249: "Empty · Silence",
	250: "Empty · Silence",
	251: "Empty · Silence",
	252: "Empty · Silence",
	253: "Empty · Silence",
	254: "Empty · Silence",
	255: "Empty · Silence",
}


# --- Silence-flavour split (ADR-0085 2026-08-12 amendment, Muted verdict) -------
# The `· Silence` category is NOT one tier: it splits by provenance into
# TRUSTED-EMPTY (provably zero output — "Empty" / "Empty/Silent") and GRAY-ZONE
# CLIP (faint but NONZERO — "Inaudible Clip" / "Nearly Inaudible Clip"). The Muted
# opcode verdict may hard-hatch a note only under a trusted-empty instrument; a
# clip note is not provably silent → the softer "faint" tell, never a hatch. These
# PARSE the NAMES strings (not hard-coded ids), so they survive regeneration.

## The category tail after " · " ("Silence", "Synth", …); "" for an unnamed id.
static func category(id: int) -> String:
	return String(NAMES.get(id, "")).get_slice(" · ", 1)


## True iff `id` is in the `· Silence` category (any flavour, empty or clip).
static func is_silence(id: int) -> bool:
	return category(id) == "Silence"


## The silence flavour of `id` — "Empty" (normalizing "Empty/Silent"), "Inaudible
## Clip", or "Nearly Inaudible Clip" — else "" (not a silence instrument). Parsed
## from the name before " · ".
static func silence_flavour(id: int) -> String:
	if not is_silence(id):
		return ""
	var head := String(NAMES.get(id, "")).get_slice(" · ", 0).strip_edges()
	return "Empty" if head.begins_with("Empty") else head


## A TRUSTED-EMPTY instrument: provably zero output. A note under it, on a voice
## that is NOT noise-armed, is Muted (hard hatch).
static func is_trusted_empty(id: int) -> bool:
	return silence_flavour(id) == "Empty"


## A GRAY-ZONE clip: faint but nonzero. NOT provably silent → never Muted; a note
## under it gets the softer "faint" ≈ tell.
static func is_gray_zone_clip(id: int) -> bool:
	var f := silence_flavour(id)
	return f == "Inaudible Clip" or f == "Nearly Inaudible Clip"
