#!/usr/bin/env python3
"""
Convert TacticsEngineG's `animation_names.txt` CSV into our project's
`assets/sprites/animation_names.json` format.

The source is a CSV with rows `type,animation_id,animation_name` covering
~2200 hand-authored labels for every SEQ slot in every sprite type — body
templates (TYPE1, TYPE2, TYPE3, TYPE4, MON, CYOKO, RUKA, ARUTE, KANZEN,
OTHER) and overlay templates (WEP1, WEP2, EFF1, EFF2). This script
normalizes the type names to our canonical lowercase keys (matching
`state_animations.json` / `reaction_animations.json`) and emits a nested
JSON keyed by sprite_type → slot_id (string) → label.

The output is treated as a *hand-authored data asset* per
godot-learning/CONTEXT.md — checked into git, never regenerated by
`bootstrap_assets.sh` (which is reserved for ROM-derived artifacts).
This converter is idempotent and re-runnable when TacticsEngineG updates
their labels.

Usage:
    uv run python tools/build_animation_names.py \\
        --source ~/TacticsEngineG/src/fftae/SeqData/animation_names.txt
"""

from __future__ import annotations

import argparse
import csv
import json
from collections import OrderedDict
from pathlib import Path

# Map TacticsEngineG's CSV `type` column to our canonical lowercase keys
# (matching state_animations.json / reaction_animations.json).
TYPE_KEY_MAP = {
    "type1": "type1",
    "type2 (Unused)": "type2",
    "type3": "type3",
    "type4 (Unused)": "type4",
    "Monster/mon": "mon",
    "Chocobo/cyoko": "cyoko",
    "Lucavi/ruka": "ruka",
    "Altima/arute": "arute",
    "Altima2/kanzen": "kanzen",
    "other": "other",
    "wep1": "wep1",
    "wep2": "wep2",
    "eff1": "eff1",
    "eff2 (Unused)": "eff2",
}


def convert(source: Path, dest: Path) -> dict:
    """Read the source CSV, return the normalized dict, and write dest JSON."""
    by_type: dict[str, dict[str, str]] = OrderedDict()
    skipped: list[str] = []

    with open(source, "r", encoding="utf-8") as f:
        reader = csv.reader(f)
        header = next(reader, None)
        if not header or header[0] != "type":
            raise ValueError(f"Unexpected header in {source}: {header}")

        for row in reader:
            if len(row) < 3:
                continue
            raw_type, slot_str, name = row[0], row[1], row[2]
            try:
                slot = int(slot_str)
            except ValueError:
                continue

            key = TYPE_KEY_MAP.get(raw_type)
            if key is None:
                skipped.append(raw_type)
                continue

            by_type.setdefault(key, OrderedDict())[str(slot)] = name

    dest.parent.mkdir(parents=True, exist_ok=True)
    with open(dest, "w", encoding="utf-8") as f:
        json.dump(by_type, f, indent=2)
        f.write("\n")

    return {
        "types_written": list(by_type.keys()),
        "rows_per_type": {k: len(v) for k, v in by_type.items()},
        "total_rows": sum(len(v) for v in by_type.values()),
        "skipped_unmapped_types": sorted(set(skipped)),
    }


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    repo_root = Path(__file__).resolve().parent.parent
    default_dest = repo_root / "assets" / "sprites" / "animation_names.json"
    p.add_argument("--source", required=True, type=Path, help="Path to TacticsEngineG animation_names.txt CSV")
    p.add_argument("--dest", type=Path, default=default_dest, help="Output JSON path (default: assets/sprites/animation_names.json)")
    args = p.parse_args()

    if not args.source.exists():
        print(f"ERROR: source CSV not found at {args.source}")
        return 1

    summary = convert(args.source, args.dest)
    print(f"Wrote {args.dest}")
    print(f"  types:     {len(summary['types_written'])}")
    print(f"  rows:      {summary['total_rows']}")
    for type_key, count in summary["rows_per_type"].items():
        print(f"    {type_key:<12} {count:>4}")
    if summary["skipped_unmapped_types"]:
        print(f"  skipped (unmapped type names): {summary['skipped_unmapped_types']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
