#!/usr/bin/env python3
"""A frozen test baseline's HEADER must still describe its BODY.

    python3 tools/check_test_baseline.py

`docs/TEST-BASELINE-E2.tsv` is a frozen measurement of one commit — the pre-move
state extraction #2 (`Audio`) is scored against (#401, ADR-0153). Its header
carries a `# tally` line that summarises the rows beneath it, and the file's own
second line says *"GENERATED by tools/freeze_test_baseline.py --tsv. Never
hand-edit."*

IT WAS HAND-EDITED ANYWAY, AND THE HEADER DID NOT NOTICE. `26d16706a` deleted
`ScenarioCameraLateralCalibTest` and removed its row, leaving `# tally … FAIL 25`
standing above a file that held 24. Two later deletions (`5146dcb9c`,
`ab6368603`) left their rows alone, which is the correct treatment — so the file
had two policies at once and no way to say so.

A FROZEN MEASUREMENT CANNOT BE RE-FROZEN, which is why "just regenerate it" is
not the fix. Re-running `freeze_test_baseline.py --tsv` today measures the
POST-move tree; the pre-move number it replaced is then gone. So a row stays
after its test is deleted — the run still happened and the tally still counts it
— and the deletion is recorded in the header's `# deleted` ledger instead.

A MOVE IS NOT A DELETION, AND THE REGISTER HAS TO BE ABLE TO SAY SO (ADR-0194
dec. 10). An addon-owned test leaves `tests/` for `addons/<name>/tests/` and is
still run — by `tests/stranger/<addon>/run.sh`, in a project that did nothing for
the addon. Recorded as `# deleted` that reads as "the run happened and the test is
gone", which is false in the half that matters, and it would repeat in the one
register built to stop it the exact defect its own header names: *"two policies at
once and no way to say so"*. So there is a second ledger kind, `# moved`, it
carries the DESTINATION, and the destination is checked to exist — a move whose
target is not there is a deletion with better paperwork.

WHAT THIS CHECKS. Four things, all mechanical:

  1. `# tally` equals the body's verdict counts, and its sum equals the row count.
  2. Every `# deleted` / `# moved` stem has a body row (a ledger entry for a row
     that is not there is the pruning this file exists to forbid) and names a
     commit; no stem is in both ledgers.
  3. Every body row whose `tests/<stem>.tscn` is gone appears in one of them. This
     is the arm that fires on the NEXT deletion or move, and it is the whole point:
     a ratchet needs both arms, or it only ever confirms the state it was written in.
  4. Every `# moved` destination EXISTS. `# deleted` has nothing to check here —
     a deleted file is gone by definition — which is why the kinds are separate
     rows and not a column on one.

Exit 0 = clean. Pure stdlib; run from the package root.
"""
import collections
import pathlib
import re
import subprocess
import sys

TSV = pathlib.Path("docs/TEST-BASELINE-E2.tsv")
# Every word `tests/lib/verdict.sh` can return. The register itself is FROZEN
# and map #450 does not touch it, so THREW (#462), CRASHED and NOT_A_TEST
# (#463) appear in no row today. They are listed anyway: the tally check
# compares a header count against a body count, and a verdict this tuple
# cannot name would be counted on one side only — a drift report about the
# guard's own vocabulary, dressed as a drift in the register.
VERDICTS = ("PASS", "FAIL", "NO_VERDICT", "TIMEOUT", "HUNG", "THREW",
            "CRASHED", "NOT_A_TEST")


def main() -> int:
    if not TSV.is_file():
        print(f"{TSV} is missing — nothing to check")
        return 0
    lines = TSV.read_text(encoding="utf-8").splitlines()
    head = [l for l in lines if l.startswith("#")]
    body = [l for l in lines if l and not l.startswith("#")]
    cols = body[0].split("\t")
    rows = [l.split("\t") for l in body[1:]]
    fail = []

    # --- 1. the tally describes the body ------------------------------------
    tally_line = next((l for l in head if l.startswith("# tally\t")), None)
    if tally_line is None:
        fail.append("no `# tally` header line — the summary this guard checks is absent")
    else:
        declared = {m.group(1): int(m.group(2))
                    for m in re.finditer(r'\b(' + "|".join(VERDICTS) + r')\s+(\d+)', tally_line)}
        actual = collections.Counter(r[cols.index("verdict")] for r in rows)
        for v in sorted(set(declared) | set(actual)):
            if declared.get(v, 0) != actual.get(v, 0):
                fail.append(f"TALLY DRIFT — header says {v} {declared.get(v, 0)}, "
                            f"the body holds {actual.get(v, 0)}")
        if sum(declared.values()) != len(rows):
            fail.append(f"TALLY SUM — header totals {sum(declared.values())}, "
                        f"the body has {len(rows)} rows")

    stems = {r[0] for r in rows}
    if len(stems) != len(rows):
        dup = [s for s, n in collections.Counter(r[0] for r in rows).items() if n > 1]
        fail.append(f"DUPLICATE ROW(S) — {', '.join(sorted(dup))}")

    # --- 2. the ledgers point at rows that are still there -------------------
    # Two kinds, one shape. The prose lines carry one field; an ENTRY is the line
    # whose SHA slot holds a sha, which is what tells the two apart without a
    # second marker: `# deleted  stem  sha  why`, `# moved  stem  dest  sha  why`.
    deleted, moved = {}, {}
    for l in head:
        for prefix, sink, sha_at in (("# deleted\t", deleted, 1), ("# moved\t", moved, 2)):
            if not l.startswith(prefix):
                continue
            parts = l.split("\t")[1:]
            if len(parts) > sha_at and re.fullmatch(r'[0-9a-f]{7,40}', parts[sha_at]):
                sink[parts[0]] = parts
    for kind, ledger, sha_at in (("deleted", deleted, 1), ("moved", moved, 2)):
        for stem, parts in sorted(ledger.items()):
            sha = parts[sha_at]
            if stem not in stems:
                fail.append(f"LEDGER WITHOUT ROW — `# {kind} {stem}` names a test whose row "
                            f"is not in the body. The row is the measurement; deleting it is "
                            f"what the ledger exists to replace.")
            if subprocess.run(["git", "cat-file", "-e", sha + "^{commit}"],
                              capture_output=True).returncode != 0:
                fail.append(f"LEDGER COMMIT — `# {kind} {stem}` names {sha}, "
                            f"which is not a commit in this repo")
    for stem in sorted(set(deleted) & set(moved)):
        fail.append(f"TWO KINDS — {stem} is recorded both `# deleted` and `# moved`. "
                    f"It is one or the other; two policies at once is the defect this "
                    f"register's own header names.")

    # --- 3. and every row whose test is gone is in one of them ---------------
    ledgered = set(deleted) | set(moved)
    for stem in sorted(stems):
        if not pathlib.Path(f"tests/{stem}.tscn").is_file() and stem not in ledgered:
            fail.append(f"UNRECORDED — {stem} has a baseline row but no tests/{stem}.tscn. "
                        f"Keep the row (a frozen measurement cannot be re-frozen) and record "
                        f"WHICH happened: `# deleted\t{stem}\t<commit>\t<why>` if it is gone, "
                        f"`# moved\t{stem}\t<destination>\t<commit>\t<why>` if it still runs "
                        f"somewhere else (ADR-0194 dec. 10).")

    # --- 4. a move names a destination that is THERE --------------------------
    for stem, parts in sorted(moved.items()):
        dest = parts[1]
        if not pathlib.Path(dest).exists():
            fail.append(f"MOVED TO NOWHERE — `# moved {stem}` names {dest}, which does not "
                        f"exist. A move whose destination is absent is a deletion, and the "
                        f"whole reason this kind exists is that the two are different.")

    if fail:
        print(f"{TSV}: {len(fail)} problem(s)\n")
        for f in fail:
            print("  " + f)
        return 1
    print(f"{TSV} OK — {len(rows)} rows, tally matches, "
          f"{len(deleted)} recorded deletion(s) and {len(moved)} recorded move(s), "
          f"none unrecorded, every destination present.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
