#!/usr/bin/env python3
"""Guard `docs/RESIDUE.tsv` — the register of built-but-unclaimed files.

`docs/RESIDUE.tsv` is GENERATED by `tools/residue.py --tsv` and must never be
hand-edited, the same contract `docs/adr/INDEX.md` has with `gen_adr_index.py`.
This re-derives it and diffs.

    python3 tools/check_residue.py

WHAT IT IS FOR. `refactor-loop.md` pass 8 requires that *every newly-unclaimed
file gets a reason*. An extraction unclaims files as a side effect — a script
left behind when its scene moved into an addon reaches nothing and is reached by
nothing — and there is no moment in the loop where anyone would think to look.
This is that moment: the register goes stale on the commit that unclaims the
file, and the guard says so with the file's name in the message.

It is deliberately a STALENESS check and not a threshold. A rising residue count
is not a defect; an UNATTRIBUTED one is. ADR-0145 dec. 6.
"""
import sys, pathlib, io, contextlib, subprocess

TSV = pathlib.Path("docs/RESIDUE.tsv")
if not TSV.exists():
    print("docs/RESIDUE.tsv is missing — run `python3 tools/residue.py --tsv`")
    sys.exit(1)

def _body(text: str) -> list[str]:
    """Rows only — drop the `#` subject line and the column header (ADR-0149)."""
    return [ln for ln in text.strip().splitlines()
            if not ln.startswith("#") and not ln.startswith("file\t")]


have = TSV.read_text(encoding="utf-8")
proc = subprocess.run([sys.executable, "tools/residue.py", "--tsv"],
                      capture_output=True, text=True)
if proc.returncode != 0:
    print("tools/residue.py failed:\n" + proc.stdout + proc.stderr)
    sys.exit(1)
want = TSV.read_text(encoding="utf-8")

if have == want:
    n = len(_body(want))
    print(f"RESIDUE.tsv OK — {n} unclaimed files, all attributed.")
    sys.exit(0)

TSV.write_text(have, encoding="utf-8")  # leave the tree as we found it
hrows = {ln.split("\t")[0]: ln for ln in _body(have)}
wrows = {ln.split("\t")[0]: ln for ln in _body(want)}
added, gone = sorted(set(wrows) - set(hrows)), sorted(set(hrows) - set(wrows))
changed = sorted(f for f in set(hrows) & set(wrows) if hrows[f] != wrows[f])

print("docs/RESIDUE.tsv is STALE. Run `python3 tools/residue.py --tsv` and commit it.\n")
for label, items in (("newly unclaimed — these need a reason", added),
                     ("no longer unclaimed", gone),
                     ("attribution changed", changed)):
    if items:
        print(f"  {label} ({len(items)}):")
        for f in items:
            print(f"    {f}")
sys.exit(1)
