#!/usr/bin/env python3
"""Split-aware index for the project vocabulary.

`CONTEXT.md` was one 9,001-line file. It is now an INDEX: the preamble, plus
one row per cluster naming the file that holds it and the terms it defines.
The prose lives in `docs/context/<nn>-<slug>.md`, one file per cluster.

Why an index and not just a directory: 423 places in this repo cite
`CONTEXT.md` and many name a term (`CONTEXT.md "Takeover mode"`). Keeping every
term listed here means that grep still lands, and the reader is one hop from
the definition instead of loading the whole vocabulary.

Generated. Do not hand-edit CONTEXT.md — edit the cluster file and re-run.
Guarded by `tools/check_context_index.py`.

Run from the package root.
"""
import pathlib, posixpath, re, sys

CTX = pathlib.Path("docs/context")
# A definition opens the line with a bold term. What follows is either nothing,
# a `:`, or a qualifying parenthetical — which may WRAP, so an unclosed "(" also
# counts. Bold used mid-prose for emphasis never matches: it has trailing text.
TERM_BOLD = re.compile(r"^\*\*([^*]+)\*\*(.*)$")


def term_of(line, following=""):
    """`following` is the rest of the file, for a qualifier that wraps lines."""
    m = TERM_BOLD.match(line)
    if not m:
        return None
    term, rest = m.group(1).strip(), m.group(2).strip()
    # The qualifier IS the disambiguator — `Span (sound)` and `Span (lane event)`
    # are two terms, not one defined twice. Keep it in the name.
    qual = ""
    if rest.startswith("("):
        close = rest.find(")")
        if close != -1:
            qual = " " + rest[: close + 1]
            rest = rest[close + 1:].strip()
        else:
            # the qualifier wraps — close it from the following text
            joined = (rest + " " + following.replace("\n", " ")).strip()
            close = joined.find(")")
            if close == -1:
                return term
            qual = " " + " ".join(joined[: close + 1].split())
            rest = joined[close + 1:].strip()
            rest = ":" if rest.startswith(":") else rest
    if rest in ("", ":") or rest.endswith(":"):
        return (term + qual).strip()
    return None
HEAD = "<!-- generated by tools/gen_context_index.py — edit docs/context/, not this file -->"

PREAMBLE = """# godot-learning — project vocabulary

Terms cluster by domain. This file is an **index**: each row names the cluster
file that holds the prose and the terms it defines. Add a term by editing its
cluster file under `docs/context/` and re-running
`uv run python tools/gen_context_index.py`.

A new cluster is a new file in `docs/context/`; the index picks it up.
"""


def clusters():
    for p in sorted(CTX.glob("[0-9][0-9]-*.md")):
        text = p.read_text(encoding="utf-8")
        title = text.splitlines()[0].lstrip("# ").strip()
        ls = text.splitlines()
        terms = [t for t in (term_of(l, "\n".join(ls[i + 1:i + 3]))
                             for i, l in enumerate(ls)) if t]
        # `#### Sub-heading`s are cited the same way a bold term is.
        terms += [l.lstrip("#").strip() for l in text.splitlines() if l.startswith("#### ")]
        yield p, title, terms, len(text.splitlines())


# A markdown link target: `](…)` with no whitespace in it.
_LINK = re.compile(r"\]\(([^)\s]+)\)")


def rehome(text):
    """Re-express a cluster's relative links against the PACKAGE ROOT.

    A cluster term can carry a link (`Boundary drag (camera edge-resize,
    [ADR-0086](../adr/0086-….md))`), and that spelling is correct where it is
    written: from `docs/context/`, `../adr/` IS `docs/adr/`. This index is
    hoisted to `CONTEXT.md` at the package root, where the same characters mean
    a repo-root `adr/` that has never existed — 31 links pointed there (#1096,
    #1097), and #1097's hand-edit of CONTEXT.md was reverted by the next run of
    THIS generator, which is what made the stale-index guard the thing that
    caught it.

    So the rewrite belongs here and not in the cluster: fixing the source would
    break the link in the file it is written in, which the guard's BROKEN LINK
    check would then catch instead. URLs, anchors and absolute paths are left
    alone."""
    def fix(m):
        target = m.group(1)
        if "://" in target or target.startswith(("#", "/", "mailto:")):
            return m.group(0)
        path, _, frag = target.partition("#")
        if not path:
            return m.group(0)
        moved = posixpath.normpath(posixpath.join(CTX.as_posix(), path))
        return "](%s%s)" % (moved, "#" + frag if frag else "")
    return _LINK.sub(fix, text)


def render():
    out = [HEAD, "", PREAMBLE, "| cluster | terms | lines |", "|---|---:|---:|"]
    rows, total_terms, total_lines = [], 0, 0
    for p, title, terms, n in clusters():
        rows.append(f"| [{rehome(title)}]({p.as_posix()}) | {len(terms)} | {n} |")
        total_terms += len(terms)
        total_lines += n
    out += rows
    out.append(f"| **{len(rows)} clusters** | **{total_terms}** | **{total_lines}** |")
    out.append("")
    out.append("## Terms")
    out.append("")
    for p, title, terms, _ in clusters():
        if not terms:
            continue
        out.append(f"**{rehome(title)}** — [`{p.name}`]({p.as_posix()})")
        out.append("")
        out.append("  " + rehome(" · ".join(sorted(terms))))
        out.append("")
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    if not CTX.is_dir():
        print("docs/context/ does not exist", file=sys.stderr)
        sys.exit(2)
    pathlib.Path("CONTEXT.md").write_text(render(), encoding="utf-8")
    n = sum(1 for _ in clusters())
    print(f"wrote CONTEXT.md — {n} clusters")
