extends Node3D
## THE MAP-BUFFER RATCHET'S GOLDEN, taken over the whole exported corpus.
##
## ADR-0224 dec. 8 makes the exported maps the A/B for the level widening: the
## GPU map buffer's level-0 block and the distance field's flat array must come
## out byte-identical to what they held before the buffer grew a second plane.
## That is only checkable against bytes recorded BEFORE the change, so this tool
## writes them, once, and `tests/GPUMapBufferLevelRatchetTest.gd` reads them back.
##
## 🔴 REGENERATING THIS FILE DISARMS THE RATCHET. The golden is a claim about
## `3f4658f3c`'s output — the commit before the widening — not about whatever the
## current tree produces. Regenerate it only when a decision deliberately moves
## those bytes, and say which decision in the commit message.
##
## What is measured lives in `tests/MapBufferCorpus.measure` and is shared with
## the test, so the two sides cannot drift into measuring different things.
##
## Run: <GODOT> --path . --quit-after 100000 res://tools/gen_map_buffer_golden.tscn

const MapBufferCorpus = preload("res://tests/MapBufferCorpus.gd")


func _ready() -> void:
	var rows: Dictionary = {}
	var upper := 0
	var t0 := Time.get_ticks_msec()
	for map_name in MapBufferCorpus.map_names():
		var terrain: Dictionary = MapBufferCorpus.load_terrain(map_name)
		if terrain.is_empty():
			print("[WARN] no readable terrain.json for %s" % map_name)
			continue
		var lattice := MapBufferCorpus.build_lattice(terrain, self)
		if MapBufferCorpus.has_upper_cells(lattice):
			upper += 1
		rows[map_name] = MapBufferCorpus.measure(lattice)
		_teardown()
	var elapsed := Time.get_ticks_msec() - t0

	var f := FileAccess.open(MapBufferCorpus.GOLDEN_PATH, FileAccess.WRITE)
	if f == null:
		print("[FAIL] cannot write %s" % MapBufferCorpus.GOLDEN_PATH)
		get_tree().quit(1)
		return
	f.store_string(JSON.stringify({
		"_comment": "Generated by tools/gen_map_buffer_golden.gd against the map buffer as it stood BEFORE ADR-0224's widening. Regenerating this disarms the ratchet in tests/GPUMapBufferLevelRatchetTest.gd.",
		"maps": rows,
	}, "\t", true) + "\n")
	f.close()
	print("=== golden: %d maps (%d with upper cells) in %d ms -> %s ===" % [
		rows.size(), upper, elapsed, MapBufferCorpus.GOLDEN_PATH])
	get_tree().quit(0)


func _teardown() -> void:
	for child in get_children():
		remove_child(child)
		child.free()
