#!/usr/bin/env python3
"""Derive `docs/TEST-AUDIT-REGISTER.tsv` — the audit loop's work list and memory.

    uv run python tools/seed_test_audit_register.py            # write the register
    uv run python tools/seed_test_audit_register.py --dry-run  # print the order only

WHY THE ORDER IS CLOSURE OVERLAP AND NOT WALL CLOCK. The obvious ordering is
slowest-test-first, and `godot-learning/CLAUDE.md` already records why it does not
pay: 59% of tests finish inside Godot's own boot cost and *"cutting slow tests
barely helps — 80% of the clock is 66% of the tests."* The suite is expensive
because it is 736 PROCESSES, not because any of them is slow. So the only lever
that moves the number is running fewer, and the mechanically-derivable candidates
for "these two tests are the same test" are the pairs whose static closures agree.

`overlap` below is a test's highest Jaccard similarity against any other test's
closure, at depth 3 — `scoped_tests.py`'s default, chosen there because unlimited
transitive closure does not discriminate in this tree (one leaf is reached by 551
of 744 scenes at 12 hops and 6 at 2). A high score is a MERGE CANDIDATE, never a
verdict: two tests can share every file they load and assert on different halves
of it. The audit reads the pair; this only decides what it reads first.

The register is the loop's memory across ~736 sessions, so every column it fills
in is evidence a morning reviewer can check without re-running anything —
particularly `seeded_break` and `survivor`, which are the whole justification for
a delete. Re-running this seeder REFUSES to clobber audited rows; it merges,
because the work list is derived and the findings are not.

Pure stdlib. Run from the package root.
"""
import argparse
import os
import pathlib
import sys

os.chdir(pathlib.Path(__file__).resolve().parent.parent)

# closure.py is a script: importing it runs its whole residue report. Swallow the
# report, keep the machinery — the same reuse (and the same reason) as
# scoped_tests.py, which says it in its own comment: re-implementing the edge
# model is how three instruments end up with three different answers.
_stdout, sys.stdout = sys.stdout, open(os.devnull, "w")
try:
    import closure as cl
    import _runner_tests
finally:
    sys.stdout.close()
    sys.stdout = _stdout

import check_test_charter as charter

REGISTER = pathlib.Path("docs/TEST-AUDIT-REGISTER.tsv")
DEPTH = 3

COLUMNS = ("test", "kind", "verdict", "measured_seconds", "stability_k_of_n",
           "closure_size", "overlap", "twin", "seeded_break", "survivor",
           "charter_violations", "commit", "date")

HEADER = """\
# docs/TEST-AUDIT-REGISTER.tsv — the test-audit loop's work list AND its memory.
#
# GENERATED by tools/seed_test_audit_register.py. Re-running it re-derives the
# ordering columns and MERGES; it never clobbers a row an audit has filled in.
#
# One row per test in `tests/run_all_tests.sh`'s array. Rows are ordered by
# `overlap` descending — a test's highest closure-Jaccard against any other test,
# at depth 3. That is the merge-candidate ordering, not a slowest-first ordering;
# the seeder's docstring says why slowest-first does not pay here.
#
# COLUMNS
#   test                 the runner's stem
#   kind                 static-guard | logic | render | gpu | stranger-rig | perf
#                        (+ ` lane-pinned`), as DECLARED in the file's header
#   verdict              -            not audited yet
#                        KEEP         audited, nothing to change
#                        SPEED        made cheaper, same kind
#                        DEMOTE       moved down the kind ladder
#                        MERGE        folded into `twin`
#                        DELETE       removed; `survivor` catches `seeded_break`
#                        FLAKY        not stable under load -> lane-pinned
#                        RED          already failing on trunk; recorded, not fixed
#   measured_seconds     solo wall clock, from the runner's --jsonl
#   stability_k_of_n     e.g. 5/5, from K repeats under synthetic load
#   closure_size         files reachable from the scene at depth 3
#   overlap              max Jaccard vs any other test's closure (0.000-1.000)
#   twin                 the test that overlap names
#   seeded_break         what was broken to prove this test CAN fail (clause 10)
#   survivor             for DELETE/MERGE: the test that still reds on seeded_break
#   charter_violations   clause ids outstanding, from check_test_charter.py
#   commit               the sha the audit landed on
#   date                 ISO date of the audit
#
# A DELETE row with an empty `survivor` is not a finished audit. That pairing is
# the entire safety story (ADR-0254) and the one thing to check in review.
"""


def scene_seeds(stem: str) -> list[str]:
    """The scene + its script, as closure.py spells paths (relative to here)."""
    out = []
    for suffix in (".tscn", ".gd"):
        p = pathlib.Path("tests") / (stem + suffix)
        if p.is_file():
            out.append(str(p))
    return out


def closure_at(seeds: list[str], depth: int) -> set[str]:
    """Depth-capped forward closure. `cl.close_over` is uncapped and the cap is
    the whole point — at 12 hops this tree's closures are all the same set."""
    frontier = {s for s in seeds if s in cl.existing}
    seen = set(frontier)
    for _ in range(depth):
        nxt = set()
        for cur in frontier:
            for t in cl.out_edges(cur):
                if t not in seen:
                    seen.add(t)
                    nxt.add(t)
        frontier = nxt
        if not frontier:
            break
    return seen


def read_existing() -> dict[str, dict]:
    if not REGISTER.is_file():
        return {}
    rows = {}
    for line in REGISTER.read_text(encoding="utf-8").splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        cells = line.split("\t")
        if cells[0] == "test":
            continue
        row = dict(zip(COLUMNS, cells + ["-"] * (len(COLUMNS) - len(cells))))
        rows[row["test"]] = row
    return rows


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    stems = _runner_tests.runner_tests(pathlib.Path("tests/run_all_tests.sh"))
    closures = {s: closure_at(scene_seeds(s), DEPTH) for s in stems}

    # Highest Jaccard against any other test. O(n^2) over 736 sets is ~270k
    # comparisons and runs in seconds; a smarter index would be a second edge
    # model to keep in sync for no gain.
    best = {}
    names = [s for s in stems if closures[s]]
    for i, a in enumerate(names):
        ca = closures[a]
        top, twin = 0.0, "-"
        for b in names:
            if a == b:
                continue
            cb = closures[b]
            inter = len(ca & cb)
            if not inter:
                continue
            j = inter / len(ca | cb)
            if j > top:
                top, twin = j, b
        best[a] = (top, twin)
    for s in stems:
        best.setdefault(s, (0.0, "-"))

    live_violations = {}
    for stem, path in charter.test_paths():
        v = charter.violations_for(stem, path)
        live_violations[stem] = ",".join(v) if v else "-"

    prior = read_existing()
    rows = []
    for stem in stems:
        overlap, twin = best[stem]
        row = prior.get(stem, {c: "-" for c in COLUMNS})
        row["test"] = stem
        # Derived columns are always re-derived; findings are never touched.
        row["closure_size"] = str(len(closures[stem]))
        row["overlap"] = f"{overlap:.3f}"
        row["twin"] = twin
        row["charter_violations"] = live_violations.get(stem, "-")
        rows.append(row)

    rows.sort(key=lambda r: (-float(r["overlap"]), r["test"]))

    if args.dry_run:
        for r in rows[:25]:
            print(f"{r['overlap']}  {r['test']:<48} closure={r['closure_size']:<5} twin={r['twin']}")
        print(f"... {len(rows)} rows total")
        return 0

    out = [HEADER, "\t".join(COLUMNS)]
    out += ["\t".join(r[c] for c in COLUMNS) for r in rows]
    REGISTER.write_text("\n".join(out) + "\n", encoding="utf-8")
    audited = len([r for r in rows if r["verdict"] not in ("-", "")])
    print(f"wrote {REGISTER} — {len(rows)} rows, {audited} already audited")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
